/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ClientesDao;
import br.com.projeto.dao.ContasRecDao;
import br.com.projeto.dao.PlanosDao;
import br.com.projeto.dao.VendasNoCartaoDao;
import br.com.projeto.model.Clientes;
import br.com.projeto.model.ContasRec;
import br.com.projeto.model.Planos;
import br.com.projeto.model.Utilitarios;
import br.com.projeto.model.VendasNoCartao;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Godoy
 */
public class FrmContaReceberBaixar extends javax.swing.JFrame {

    FrmContaReceberFiltro contFil = new FrmContaReceberFiltro();
    FrmPlanosFiltro plaFil = new FrmPlanosFiltro();

    double total = 0;
    double valor;
    double taxa = 0;
    double desconto = 0;
    double totalRec = 0; //o total a receber.
    double valorFinal = 0; // será usado pra cadastrar venda cartão, é o valor final descontado a taxa.
    int cliente; //será usado no form de recibo.
    int linhas = 0; //pra ver se tem alguma conta selecionada, se não tiver não abre a tela de recibo.

    DecimalFormat decimal = new DecimalFormat("#,##0.00");

    public FrmContaReceberBaixar() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFiltrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContasReceber = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBaixar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdPlano = new javax.swing.JTextField();
        txtPlano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtPagamento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblTotalReceber = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(173, 198, 242));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Baixar Contas a Receber");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/filtro.png"))); // NOI18N
        btnFiltrar.setToolTipText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/impressora.png"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir Recibo");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFiltrar)
            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbContasReceber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbContasReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OK", "Título", "Requisição", "Cliente", "Emissão", "Vencimento", "Valor Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbContasReceber.setRowHeight(20);
        tbContasReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbContasReceberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbContasReceber);
        if (tbContasReceber.getColumnModel().getColumnCount() > 0) {
            tbContasReceber.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbContasReceber.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbContasReceber.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbContasReceber.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total a Baixar:");

        btnBaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/baixar.png"))); // NOI18N
        btnBaixar.setToolTipText("Baixar");
        btnBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Plano:");

        txtIdPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdPlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdPlanoMouseClicked(evt);
            }
        });
        txtIdPlano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdPlanoKeyPressed(evt);
            }
        });

        txtPlano.setEditable(false);
        txtPlano.setBackground(new java.awt.Color(255, 255, 255));
        txtPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qtd.:");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQuantidade.setText("1");
        txtQuantidade.setEnabled(false);

        txtPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pagamento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tipo:");

        txtTipo.setEditable(false);
        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTipoMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total a Receber:");

        lblTotalReceber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalReceber.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPlano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTotalReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBaixar))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        totalRec = 0;
        contFil.mostrarTela(this);
        contFil.lblTitulo.setText("Relatório de Contas a Receber");

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void tbContasReceberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContasReceberMouseClicked

        boolean ativo;

        /**
         * seleciona as contas que serão baixadas.
         */
        if (evt.getClickCount() == 2) {
            ativo = Boolean.parseBoolean(tbContasReceber.getValueAt(tbContasReceber.getSelectedRow(), 0).toString());

            if (ativo == false) {
                tbContasReceber.setValueAt(true, tbContasReceber.getSelectedRow(), 0);
                valor = Double.parseDouble(tbContasReceber.getValueAt(tbContasReceber.getSelectedRow(), 6).toString().replace(".", "").replace(",", "."));
                total += valor;
                txtTotal.setText(String.valueOf(decimal.format(total)));
                linhas += 1;
            } else {
                tbContasReceber.setValueAt(false, tbContasReceber.getSelectedRow(), 0);
                valor = Double.parseDouble(tbContasReceber.getValueAt(tbContasReceber.getSelectedRow(), 6).toString().replace(".", "").replace(",", "."));
                total -= valor;
                txtTotal.setText(String.valueOf(decimal.format(total)));
                linhas -= 1;
            }

        }

    }//GEN-LAST:event_tbContasReceberMouseClicked

    private void txtIdPlanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdPlanoMouseClicked

        if (evt.getClickCount() == 2) {
            plaFil.mostrarTela(this);
        }

    }//GEN-LAST:event_txtIdPlanoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        Date hoje = new Date();
        txtPagamento.setDate(hoje);

        DefaultTableModel tabelaContas = (DefaultTableModel) tbContasReceber.getModel();

        // caso não tenho nenhuma conta na tabela, o total inicia com zero, senão ele inicial com o valor de todas as contas.
        int linhas = tabelaContas.getRowCount();
        totalRec = 0;
        if (linhas == 0) {
            lblTotalReceber.setText("0");
        } else {
            for (int i = 0; i < linhas; i++) {
                double valorLin = Double.parseDouble(tabelaContas.getValueAt(i, 6).toString().replace(".", "").replace(",", "."));
                totalRec += valorLin;
            }
            lblTotalReceber.setText(String.valueOf(decimal.format(totalRec)));
        }

    }//GEN-LAST:event_formWindowActivated

    private void btnBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarActionPerformed

        DefaultTableModel contasBaixar = (DefaultTableModel) tbContasReceber.getModel();
        boolean ativo;
        String plano = txtPlano.getText();
        Date pagamento = txtPagamento.getDate();

        ContasRecDao dao = new ContasRecDao();
        ContasRec obj = new ContasRec();

        if (plano.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o plano e a data do pagamento!");
        } else {

            /**
             * faz a checagem se a conta está marcada para ser baixada, se
             * estiver é feito a baixa, senão mantém como está e passa pra linha
             * de baixo.
             */
            for (int i = 0; i < contasBaixar.getRowCount(); i++) {
                ativo = Boolean.parseBoolean(contasBaixar.getValueAt(i, 0).toString()); //verifico se a linha da tabela está marcada
                if (ativo == true) { //se estiver marcada entra no if.
                    obj.setId(contasBaixar.getValueAt(i, 1).toString());
                    obj.setSituacao("Liq");

                    Planos objPla = new Planos();
                    objPla.setId(Integer.parseInt(txtIdPlano.getText()));
                    obj.setPlano(objPla);

                    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                    pagamento = txtPagamento.getDate();
                    String pagamentoFor = formato.format(pagamento);
                    obj.setBaixa(pagamentoFor);

                    dao.baixarEstornar(obj);

                }

            }

            //  remove as contas baixadas da tabela. 
            for (int i = 0; i < contasBaixar.getRowCount(); i++) {
                ativo = Boolean.parseBoolean(contasBaixar.getValueAt(i, 0).toString()); //verifico se a linha da tabela está marcada.
                if (ativo == true) {
                    contasBaixar.removeRow(i);
                    i = i - 1;
                }
            }

            //essa parte é para lançar a venda no cartão, caso tenha.
            String tipo = txtTipo.getText();

            if (tipo.equals("Crédito") || tipo.equals("Débito")) {
                VendasNoCartao objCart = new VendasNoCartao();
                VendasNoCartaoDao daoCart = new VendasNoCartaoDao();
                Planos objPla = new Planos();

                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                String pagamentoFor = formato.format(pagamento);

                if (tipo.equals("Débito")) {
                    objCart.setEmissao(pagamentoFor);
                    objCart.setVencimento(pagamentoFor);
                    objCart.setSituacao("A baixar");
                    objCart.setValorVenda(total);
                    desconto = (total / 100) * taxa;
                    objCart.setDesconto(desconto);
                    valorFinal = total - desconto;
                    objCart.setValorFinal(valorFinal);
                    int id_plano = Integer.parseInt(txtIdPlano.getText());
                    objPla.setId(id_plano);
                    objCart.setPlano(objPla);
                    daoCart.inserir(objCart);
                } else {
                    Date vencimento = pagamento;
                    int dias = 30;
                    int qtdParc = Integer.parseInt(txtQuantidade.getText());
                    double valorParc = total / qtdParc;
                    Calendar c = Calendar.getInstance();
                    c.setTime(vencimento);
                    String vencimentoFor;

                    for (int i = 0; i < qtdParc; i++) {
                        objCart.setEmissao(pagamentoFor);
                        c.add(Calendar.DATE, +dias);
                        vencimento = c.getTime();
                        vencimentoFor = formato.format(vencimento);
                        objCart.setVencimento(vencimentoFor);
                        objCart.setSituacao("A baixar");
                        objCart.setValorVenda(valorParc);
                        desconto = (valorParc / 100) * taxa;
                        objCart.setDesconto(desconto);
                        valorFinal = valorParc - desconto;
                        objCart.setValorFinal(valorFinal);
                        int id_plano = Integer.parseInt(txtIdPlano.getText());
                        objPla.setId(id_plano);
                        objCart.setPlano(objPla);
                        daoCart.inserir(objCart);
                    }
                }
            }
            totalRec -= total;
            lblTotalReceber.setText(String.valueOf(decimal.format(totalRec)));
            valor = 0;
            total = 0;
            desconto = 0;
            valorFinal = 0;
            txtTotal.setText("");
            JOptionPane.showMessageDialog(null, "Arquivo baixado com sucesso!");
        }


    }//GEN-LAST:event_btnBaixarActionPerformed

    private void txtTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        /**
         * mostra na tela de recibos, todas as contas que foram selecionadas
         * como pagas.
         */
        if (linhas == 0) {
            JOptionPane.showMessageDialog(null, "Selecione as contas que deseja imprimir o recibo!");
        } else {
            FrmContaReceberBaixarRecibo tela = new FrmContaReceberBaixarRecibo();
            tela.setVisible(true);

            ClientesDao daoCli = new ClientesDao();
            Clientes objCli = new Clientes();
            objCli = daoCli.consultarPorId(cliente);

            tela.lblNome.setText(objCli.getNome());

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date pagamento = txtPagamento.getDate();
            String pagamentoFor = formato.format(pagamento);
            tela.lblPagamento.setText(pagamentoFor);
            tela.lblTotal.setText(txtTotal.getText());

            DefaultTableModel contasBaixar = (DefaultTableModel) tbContasReceber.getModel();
            boolean ativo;
            String titulo = "", tit = "";
            String emissao = "", emis = "";
            String vencimento = "", venc = "";
            String valor = "", val = "";

            for (int i = 0; i < contasBaixar.getRowCount(); i++) {
                ativo = Boolean.parseBoolean(contasBaixar.getValueAt(i, 0).toString());
                if (ativo == true) {
                    tit = contasBaixar.getValueAt(i, 1).toString();
                    titulo = titulo + tit + "<br>";
                    emis = contasBaixar.getValueAt(i, 4).toString();
                    emissao = emissao + emis + "<br>";
                    venc = contasBaixar.getValueAt(i, 5).toString();
                    vencimento = vencimento + venc + "<br>";
                    val = contasBaixar.getValueAt(i, 6).toString();
                    valor = valor + val + "<br>";
                }
            }

            tela.lblTitulo.setText("<html>" + titulo + "</html>");
            tela.lblEmissao.setText("<html>" + emissao + "</html>");
            tela.lblVencimento.setText("<html>" + vencimento + "</html>");
            tela.lblValor.setText("<html>" + valor + "</html>");
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtIdPlanoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPlanoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Planos objPla = new Planos();
            PlanosDao daoPla = new PlanosDao();
            int id = Integer.parseInt(txtIdPlano.getText());
            objPla = daoPla.consultarPorId(id);

            txtPlano.setText(objPla.getNome());
            txtTipo.setText(objPla.getTipo());
            taxa = objPla.getPorcentagem();

            String tipo = objPla.getTipo();
            if (tipo.equals("Crédito")) {
                txtQuantidade.setEnabled(true);
                txtQuantidade.requestFocus();
                txtQuantidade.selectAll();
            } else {
                txtQuantidade.setEnabled(false);
                txtQuantidade.setText("1");
            }
        }
    }//GEN-LAST:event_txtIdPlanoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContaReceberBaixar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContaReceberBaixar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContaReceberBaixar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContaReceberBaixar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContaReceberBaixar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaixar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalReceber;
    public javax.swing.JTable tbContasReceber;
    public javax.swing.JTextField txtIdPlano;
    private com.toedter.calendar.JDateChooser txtPagamento;
    public javax.swing.JTextField txtPlano;
    public javax.swing.JTextField txtQuantidade;
    public javax.swing.JTextField txtTipo;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
