/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ClientesDao;
import br.com.projeto.dao.FornecedoresDao;
import br.com.projeto.model.Clientes;
import br.com.projeto.model.Fornecedores;
import br.com.projeto.model.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Godoy
 */
public class FrmFornecedoresFiltro extends javax.swing.JFrame {

    private String origem = null; // Variável para determinar qual form chamou esse, assim determina quais ações serão executadas
    // de acordo com a origem em questão.

    /**
     * Os métodos mostrarTela especifica qual form chamou esse, esse form pode
     * trocar informações (buscar e levar) com o form que o chamou.
     */
    private FrmFornecedores fornecedores;

    public void mostrarTela(FrmFornecedores forn) {
        this.fornecedores = forn;
        this.origem = "fornecedores";
        setVisible(true);
    }

    private FrmCompras compras;

    public void mostrarTela(FrmCompras comp) {
        this.compras = comp;
        this.origem = "requisicao";
        setVisible(true);
    }

    private FrmContaPagarFiltro contasPagarFiltro;

    public void mostrarTela(FrmContaPagarFiltro contPagFil) {
        this.contasPagarFiltro = contPagFil;
        this.origem = "contasPagarFiltro";
        setVisible(true);
    }

    private FrmComprasContaPagLiq contasPagarLiq;

    public void mostrarTela(FrmComprasContaPagLiq contPagLiq) {
        this.contasPagarLiq = contPagLiq;
        this.origem = "contasPagarLiq";
        setVisible(true);
    }

    private FrmComprasContaPagar contasPagar;

    public void mostrarTela(FrmComprasContaPagar contPag) {
        this.contasPagar = contPag;
        this.origem = "contasPagar";
        setVisible(true);
    }

    private FrmComprasFiltroReq comprasFiltro;

    public void mostrarTela(FrmComprasFiltroReq compFil) {
        this.comprasFiltro = compFil;
        this.origem = "comprasFiltro";
        setVisible(true);
    }

    public FrmFornecedoresFiltro() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Fornecedores = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro de Fornecedores");
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(173, 198, 242));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        btnOk.setToolTipText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        tb_Fornecedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_Fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Razão Social", "CNPJ", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Fornecedores.setRowHeight(20);
        jScrollPane1.setViewportView(tb_Fornecedores);
        if (tb_Fornecedores.getColumnModel().getColumnCount() > 0) {
            tb_Fornecedores.getColumnModel().getColumn(0).setPreferredWidth(20);
            tb_Fornecedores.getColumnModel().getColumn(1).setPreferredWidth(180);
            tb_Fornecedores.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtrar Fornecedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        String texto = txtNome.getText();

        DefaultTableModel dados = (DefaultTableModel) tb_Fornecedores.getModel();
        dados.setNumRows(0);
        FornecedoresDao dao = new FornecedoresDao();

        if (texto.equals("")) {

            List<Fornecedores> lista = dao.listarFornecedores();

            for (Fornecedores f : lista) {
                dados.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getCnpj(),
                    f.getTelefone()
                });
            }
        } else {

            String nome = txtNome.getText() + "%";

            List<Fornecedores> lista = dao.consultarPorNome(nome);

            for (Fornecedores f : lista) {
                dados.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getCnpj(),
                    f.getTelefone()
                });
            }
        }


    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        /**
         * trará as informações de acordo com o cliente selecionado, e retornará
         * somente as informações pertinentes, ou seja, dependendo do form de
         * origem, ele retornará as informções que aquele form precisa.
         */
        if (origem.equals("fornecedores")) {
            int idValidacao = tb_Fornecedores.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                if (origem.equals("fornecedores")) {
                    int id = Integer.parseInt(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 0).toString());

                    FornecedoresDao dao = new FornecedoresDao();
                    Fornecedores obj = new Fornecedores();

                    obj = dao.consultarPorId(id);

                    fornecedores.filtro = "sim";

                    fornecedores.txtId.setText(String.valueOf(obj.getId()));
                    fornecedores.txtRazao.setText(obj.getNome());
                    fornecedores.txtCnpj.setText(obj.getCnpj());
                    fornecedores.txtIE.setText(obj.getIe());
                    fornecedores.txtTelefone.setText(obj.getTelefone());
                    fornecedores.txtCelular.setText(obj.getCelular());
                    fornecedores.txtEmail.setText(obj.getEmail());
                    fornecedores.txtEndereco.setText(obj.getEndereco());
                    fornecedores.txtNumero.setText(obj.getNumero());
                    fornecedores.txtComplemento.setText(obj.getComplemento());
                    fornecedores.txtBairro.setText(obj.getBairro());
                    fornecedores.txtCidade.setText(obj.getCidade());
                    fornecedores.cbUf.setSelectedItem(obj.getUf());
                    fornecedores.txtCep.setText(obj.getCep());
                    fornecedores.txtObservacoes.setText(obj.getObservacoes());

                    this.dispose();
                }

            }
        } else if (origem.equals("comprasFiltro")) {
            int idValidacao = tb_Fornecedores.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {

                comprasFiltro.txtFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 0).toString());
                this.dispose();
            }

        } else if (origem.equals("requisicao")) {
            int idValidacao = tb_Fornecedores.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {

                compras.txtIdFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 0).toString());
                compras.txtNomeFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 1).toString());
                this.dispose();
            }

        } else if (origem.equals("contasPagarFiltro")) {
            int idValidacao = tb_Fornecedores.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                contasPagarFiltro.txtFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 0).toString());
                this.dispose();
            }

        } else if (origem.equals("contasPagarLiq")) {
            int idValidacao = tb_Fornecedores.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                contasPagarLiq.txtIdFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 0).toString());
                contasPagarLiq.txtFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 1).toString());
                contasPagarLiq.txtIdPlano.requestFocus();
                contasPagarLiq.txtIdPlano.selectAll();
                this.dispose();
            }

        } else if (origem.equals("contasPagar")) {
            int idValidacao = tb_Fornecedores.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                contasPagar.txtIdFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 0).toString());
                contasPagar.txtFornecedor.setText(tb_Fornecedores.getValueAt(tb_Fornecedores.getSelectedRow(), 1).toString());
                contasPagar.txtIdPlano.requestFocus();
                contasPagar.txtIdPlano.selectAll();
                this.dispose();
            }

        }


    }//GEN-LAST:event_btnOkActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed

        String texto = txtNome.getText();

        DefaultTableModel dados = (DefaultTableModel) tb_Fornecedores.getModel();
        dados.setNumRows(0);
        FornecedoresDao dao = new FornecedoresDao();

        if (texto.equals("")) {

            List<Fornecedores> lista = dao.listarFornecedores();

            for (Fornecedores f : lista) {
                dados.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getCnpj(),
                    f.getTelefone()
                });
            }
        } else {

            String nome = txtNome.getText() + "%";

            List<Fornecedores> lista = dao.consultarPorNome(nome);

            for (Fornecedores f : lista) {
                dados.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getCnpj(),
                    f.getTelefone()
                });
            }
        }

    }//GEN-LAST:event_txtNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedoresFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedoresFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedoresFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedoresFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedoresFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tb_Fornecedores;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
