/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ClientesDao;
import br.com.projeto.dao.ProdutosDao;
import br.com.projeto.model.Clientes;
import br.com.projeto.model.Produtos;
import br.com.projeto.model.Utilitarios;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Godoy
 */
public class FrmProdutos extends javax.swing.JFrame {

    String botao = null; // variável para guardar se um cadastro está sendo criado/editado.
    String filtro = null; // variável para determinar se essa é a primeiro chamada do form, ou se ele é já recebeu dados de um select.

    String valorCompra, margemLucro, valorVenda, descontoVista, valorVista;
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat decimal = new DecimalFormat("#,##0.00");

    FrmProdutosFiltro proFil = new FrmProdutosFiltro();

    public FrmProdutos() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtNcm = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValorCompra = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        txtCod_barras = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMargem_lucro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDesconto_vista = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtValor_vista = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAtualizacao = new com.toedter.calendar.JDateChooser();
        observacoes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(173, 198, 242));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        botoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botoes.setPreferredSize(new java.awt.Dimension(850, 65));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/filtro.png"))); // NOI18N
        btnFiltrar.setToolTipText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/apagar.png"))); // NOI18N
        btnApagar.setToolTipText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesLayout = new javax.swing.GroupLayout(botoes);
        botoes.setLayout(botoesLayout);
        botoesLayout.setHorizontalGroup(
            botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesLayout.createSequentialGroup()
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botoesLayout.setVerticalGroup(
            botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(botoesLayout.createSequentialGroup()
                .addGroup(botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NCM:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cód. Barras:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quantidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Valor Compra:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtNcm.setEditable(false);
        txtNcm.setBackground(new java.awt.Color(255, 255, 255));
        txtNcm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNcm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNcmKeyPressed(evt);
            }
        });

        txtQuantidade.setEditable(false);
        txtQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        txtValorCompra.setEditable(false);
        txtValorCompra.setBackground(new java.awt.Color(255, 255, 255));
        txtValorCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorCompraKeyPressed(evt);
            }
        });

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peças Carro", "Ferramentas", "Ferragens" }));
        cbTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoKeyPressed(evt);
            }
        });

        txtCod_barras.setEditable(false);
        txtCod_barras.setBackground(new java.awt.Color(255, 255, 255));
        txtCod_barras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCod_barras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_barrasKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Valor Venda:");

        txtValorVenda.setEditable(false);
        txtValorVenda.setBackground(new java.awt.Color(255, 255, 255));
        txtValorVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorVendaKeyPressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/peças.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Marg. Lucro:");

        txtMargem_lucro.setEditable(false);
        txtMargem_lucro.setBackground(new java.awt.Color(255, 255, 255));
        txtMargem_lucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMargem_lucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMargem_lucroKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("desc. à vista:");

        txtDesconto_vista.setEditable(false);
        txtDesconto_vista.setBackground(new java.awt.Color(255, 255, 255));
        txtDesconto_vista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesconto_vista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDesconto_vistaKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Valor à Vista: ");

        txtValor_vista.setEditable(false);
        txtValor_vista.setBackground(new java.awt.Color(255, 255, 255));
        txtValor_vista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor_vista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValor_vistaKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("%");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("%");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Preço atualizado em:");

        txtAtualizacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAtualizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAtualizacaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dadosLayout = new javax.swing.GroupLayout(dados);
        dados.setLayout(dadosLayout);
        dadosLayout.setHorizontalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosLayout.createSequentialGroup()
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMargem_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCod_barras)))
                        .addGap(12, 12, 12)
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesconto_vista, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor_vista, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        dadosLayout.setVerticalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosLayout.createSequentialGroup()
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCod_barras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dadosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtMargem_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtDesconto_vista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtValor_vista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15))
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        observacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Observações"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtObservacoes.setEditable(false);
        txtObservacoes.setColumns(20);
        txtObservacoes.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        javax.swing.GroupLayout observacoesLayout = new javax.swing.GroupLayout(observacoes);
        observacoes.setLayout(observacoesLayout);
        observacoesLayout.setHorizontalGroup(
            observacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        observacoesLayout.setVerticalGroup(
            observacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoes, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
            .addComponent(observacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(observacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else {
            botao = "novo";

            btnNovo.setSelected(true);

            new Utilitarios().limpaTela_Habilita(dados);

            txtId.setEditable(false);
            cbTipo.setEditable(true);
            cbTipo.setSelectedItem("Peças Carro");
            txtObservacoes.setEditable(true);
            txtObservacoes.setText("");
            txtDesconto_vista.setText("5"); // o campo de desconto começa com 5% por padrão
            Date hoje = new Date();
            txtAtualizacao.setDate(hoje);
        }


    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated


    }//GEN-LAST:event_formWindowActivated

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (botao == "novo") {

            ProdutosDao dao = new ProdutosDao();
            Produtos obj = new Produtos();
            obj.setNome(txtNome.getText());
            obj.setTipo(cbTipo.getSelectedItem().toString());
            obj.setNcm(txtNcm.getText());
            obj.setCod_barras(txtCod_barras.getText());
            obj.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            Date atualizacao = txtAtualizacao.getDate();
            String atualizacaoS = formato.format(atualizacao);
            obj.setAtualizacao(atualizacaoS);
            valorCompra = txtValorCompra.getText();
            valorCompra = valorCompra.replace(".", "").replace(",", ".");
            obj.setValor_compra(Double.parseDouble(valorCompra));
            margemLucro = txtMargem_lucro.getText();
            margemLucro = margemLucro.replace(".", "").replace(",", ".");
            obj.setMargem_lucro(Double.parseDouble(margemLucro));
            valorVenda = txtValorVenda.getText();
            valorVenda = valorVenda.replace(".", "").replace(",", ".");
            obj.setValor_venda(Double.parseDouble(valorVenda));
            descontoVista = txtDesconto_vista.getText();
            descontoVista = descontoVista.replace(".", "").replace(",", ".");
            obj.setDesconto_vista(Double.parseDouble(descontoVista));
            valorVista = txtValor_vista.getText();
            valorVista = valorVista.replace(".", "").replace(",", ".");
            obj.setValor_vista(Double.parseDouble(valorVista));
            obj.setObservacoes(txtObservacoes.getText());

            dao.inserir(obj);

            int id = dao.ultimoCadastro();
            txtId.setText(String.valueOf(id));

            new Utilitarios().Desabilita_Apenas(dados);
            cbTipo.setEditable(false);
            txtObservacoes.setEditable(false);

            botao = null;
            btnNovo.setSelected(false);

        } else if (botao == "editar") {

            ProdutosDao dao = new ProdutosDao();
            Produtos obj = new Produtos();

            obj.setId(Integer.parseInt(txtId.getText()));
            obj.setNome(txtNome.getText());
            obj.setTipo(cbTipo.getSelectedItem().toString());
            obj.setNcm(txtNcm.getText());
            obj.setCod_barras(txtCod_barras.getText());
            obj.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            Date atualizacao = txtAtualizacao.getDate();
            String atualizacaoS = formato.format(atualizacao);
            obj.setAtualizacao(atualizacaoS);
            valorCompra = txtValorCompra.getText();
            valorCompra = valorCompra.replace(".", "").replace(",", ".");
            obj.setValor_compra(Double.parseDouble(valorCompra));
            margemLucro = txtMargem_lucro.getText();
            margemLucro = margemLucro.replace(".", "").replace(",", ".");
            obj.setMargem_lucro(Double.parseDouble(margemLucro));
            valorVenda = txtValorVenda.getText();
            valorVenda = valorVenda.replace(".", "").replace(",", ".");
            obj.setValor_venda(Double.parseDouble(valorVenda));
            descontoVista = txtDesconto_vista.getText();
            descontoVista = descontoVista.replace(".", "").replace(",", ".");
            obj.setDesconto_vista(Double.parseDouble(descontoVista));
            valorVista = txtValor_vista.getText();
            valorVista = valorVista.replace(".", "").replace(",", ".");
            obj.setValor_vista(Double.parseDouble(valorVista));
            obj.setObservacoes(txtObservacoes.getText());

            dao.editar(obj);

            new Utilitarios().Desabilita_Apenas(dados);
            cbTipo.setEditable(false);
            txtObservacoes.setEditable(false);

            botao = null;
            btnEditar.setSelected(false);
        } else {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser salvo!");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        if (botao == null) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser cancelado!");
        } else if (botao.equals("novo")) {

            new Utilitarios().limpaTela_Desabilita(dados);
            cbTipo.setEditable(false);
            cbTipo.setSelectedItem("Peças Carro");
            txtObservacoes.setEditable(false);
            txtObservacoes.setText("");
            txtAtualizacao.setCalendar(null);

            botao = null;
            btnNovo.setSelected(false);

        } else if (botao.equals("editar")) {

            int id = Integer.parseInt(txtId.getText());

            ProdutosDao dao = new ProdutosDao();
            Produtos obj = new Produtos();
            obj = dao.consultarPorId(id);

            new Utilitarios().Desabilita_Apenas(dados);
            cbTipo.setEditable(false);
            txtObservacoes.setEditable(false);

            txtNome.setText(obj.getNome());
            cbTipo.setSelectedItem(obj.getTipo());
            txtNcm.setText(obj.getNcm());
            txtCod_barras.setText(obj.getCod_barras());
            txtQuantidade.setText(String.valueOf(obj.getQuantidade()));

            txtValorCompra.setText(String.valueOf(decimal.format(obj.getValor_compra())));
            txtMargem_lucro.setText(String.valueOf(decimal.format(obj.getMargem_lucro())));
            txtValorVenda.setText(String.valueOf(decimal.format(obj.getValor_venda())));
            txtDesconto_vista.setText(String.valueOf(decimal.format(obj.getDesconto_vista())));
            txtValor_vista.setText(String.valueOf(decimal.format(obj.getValor_vista())));
            txtObservacoes.setText(obj.getObservacoes());
            String atualizacaoS = obj.getAtualizacao();
            try {
                Date atualizacao = formato.parse(atualizacaoS);
                txtAtualizacao.setDate(atualizacao);
            } catch (ParseException ex) {

            }
            botao = null;
            btnEditar.setSelected(false);

        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else {
            proFil.mostrarTela(this);
            DefaultTableModel tb_filtro = (DefaultTableModel) proFil.tb_Produtos.getModel();
            tb_filtro.setNumRows(0);
        }

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        String id = txtId.getText();

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser alterado!");
        } else if (botao == null && id != null) {
            botao = "editar";
            btnEditar.setSelected(true);

            new Utilitarios().Habilita_Apenas(dados);

            txtId.setEditable(false);
            cbTipo.setEditable(true);
            txtObservacoes.setEditable(true);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed

        String idS = txtId.getText();

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (idS.equals("")) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser excluído!");
        } else {
            int id = Integer.parseInt(txtId.getText());

            ProdutosDao dao = new ProdutosDao();
            dao.excluir(id);

            new Utilitarios().limpaTela_Desabilita(dados);
            cbTipo.setSelectedItem("Peças Carro");
            txtAtualizacao.setCalendar(null);
            txtObservacoes.setText("");
        }

    }//GEN-LAST:event_btnApagarActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQuantidade.requestFocus();
            txtQuantidade.selectAll();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNcmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNcmKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCod_barras.requestFocus();
            txtCod_barras.selectAll();
        }

    }//GEN-LAST:event_txtNcmKeyPressed

    private void txtCod_barrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_barrasKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAtualizacao.requestFocus();
        }
    }//GEN-LAST:event_txtCod_barrasKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbTipo.requestFocus();
        }
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtValorCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCompraKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String margem_lucro = txtMargem_lucro.getText();
            String valorCompraS, margemS, descontoS;
            double valorCompra, margem, valorVenda, desconto, valorVista;

            valorCompraS = txtValorCompra.getText();
            valorCompraS = valorCompraS.replace(".", "").replace(",", ".");
            valorCompra = Double.parseDouble(valorCompraS);
            txtValorCompra.setText(String.valueOf(decimal.format((valorCompra))));

            if (margem_lucro.equals("")) {

            } else {

                margemS = txtMargem_lucro.getText();
                margemS = margemS.replace(".", "").replace(",", ".");
                margem = Double.parseDouble(margemS);
                txtMargem_lucro.setText(String.valueOf(decimal.format((margem))));

                valorVenda = valorCompra + ((valorCompra / 100) * margem);
                txtValorVenda.setText(String.valueOf(decimal.format((valorVenda))));

                descontoS = txtDesconto_vista.getText();
                descontoS = descontoS.replace(".", "").replace(",", ".");
                desconto = Double.parseDouble(descontoS);
                txtDesconto_vista.setText(String.valueOf(decimal.format((desconto))));

                valorVista = valorVenda - ((valorVenda / 100) * desconto);
                txtValor_vista.setText(String.valueOf(decimal.format(valorVista)));
            }
            txtMargem_lucro.requestFocus();
            txtMargem_lucro.selectAll();
        }
    }//GEN-LAST:event_txtValorCompraKeyPressed

    private void txtMargem_lucroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargem_lucroKeyPressed

        // pega o valor de compra, e com a margem de lucro, faz o cálculo pra venda à prazo e à vista.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValorVenda.requestFocus();
            txtValorVenda.selectAll();

            String valorCompraS, margemS, descontoS;
            double valorCompra, margem, valorVenda, desconto, valorVista;

            valorCompraS = txtValorCompra.getText();
            valorCompraS = valorCompraS.replace(".", "").replace(",", ".");
            valorCompra = Double.parseDouble(valorCompraS);
            txtValorCompra.setText(String.valueOf(decimal.format((valorCompra))));

            margemS = txtMargem_lucro.getText();
            margemS = margemS.replace(".", "").replace(",", ".");
            margem = Double.parseDouble(margemS);
            txtMargem_lucro.setText(String.valueOf(decimal.format((margem))));

            valorVenda = valorCompra + ((valorCompra / 100) * margem);
            txtValorVenda.setText(String.valueOf(decimal.format((valorVenda))));

            descontoS = txtDesconto_vista.getText();
            descontoS = descontoS.replace(".", "").replace(",", ".");
            desconto = Double.parseDouble(descontoS);
            txtDesconto_vista.setText(String.valueOf(decimal.format((desconto))));

            valorVista = valorVenda - ((valorVenda / 100) * desconto);
            txtValor_vista.setText(String.valueOf(decimal.format(valorVista)));
        }
    }//GEN-LAST:event_txtMargem_lucroKeyPressed

    private void txtValorVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorVendaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDesconto_vista.requestFocus();
            txtDesconto_vista.selectAll();
        }
    }//GEN-LAST:event_txtValorVendaKeyPressed

    private void txtDesconto_vistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesconto_vistaKeyPressed

        // pega o valor de venda à prazo, e com o desconto à vista, faz o cálculo pra venda à vista.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValor_vista.requestFocus();
            txtValor_vista.selectAll();

            String valorVendaS, descontoS;
            double valorVenda, desconto, valorVista;

            valorVendaS = txtValorVenda.getText();
            valorVendaS = valorVendaS.replace(".", "").replace(",", ".");
            valorVenda = Double.parseDouble(valorVendaS);
            txtValorVenda.setText(String.valueOf(decimal.format((valorVenda))));

            descontoS = txtDesconto_vista.getText();
            descontoS = descontoS.replace(".", "").replace(",", ".");
            desconto = Double.parseDouble(descontoS);
            txtDesconto_vista.setText(String.valueOf(decimal.format((desconto))));

            valorVista = valorVenda - ((valorVenda / 100) * desconto);
            txtValor_vista.setText(String.valueOf(decimal.format(valorVista)));

        }
    }//GEN-LAST:event_txtDesconto_vistaKeyPressed

    private void txtValor_vistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor_vistaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtObservacoes.requestFocus();
            txtObservacoes.selectAll();

        }
    }//GEN-LAST:event_txtValor_vistaKeyPressed

    private void txtAtualizacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtualizacaoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValorCompra.requestFocus();
            txtValorCompra.selectAll();
        }

    }//GEN-LAST:event_txtAtualizacaoKeyPressed

    private void cbTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNcm.requestFocus();
            txtNcm.selectAll();
        }
    }//GEN-LAST:event_cbTipoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoes;
    public javax.swing.JButton btnApagar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnFiltrar;
    public javax.swing.JButton btnNovo;
    public javax.swing.JButton btnSair;
    public javax.swing.JButton btnSalvar;
    public javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JPanel dados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel observacoes;
    public com.toedter.calendar.JDateChooser txtAtualizacao;
    public javax.swing.JTextField txtCod_barras;
    public javax.swing.JTextField txtDesconto_vista;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtMargem_lucro;
    public javax.swing.JTextField txtNcm;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextArea txtObservacoes;
    public javax.swing.JTextField txtQuantidade;
    public javax.swing.JTextField txtValorCompra;
    public javax.swing.JTextField txtValorVenda;
    public javax.swing.JTextField txtValor_vista;
    // End of variables declaration//GEN-END:variables
}
