/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ClientesDao;
import br.com.projeto.dao.FuncionariosDao;
import br.com.projeto.dao.ProdutosDao;
import br.com.projeto.model.Clientes;
import br.com.projeto.model.Funcionarios;
import br.com.projeto.model.Produtos;
import br.com.projeto.model.Situacao;
import br.com.projeto.model.Utilitarios;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Godoy
 */
public class FrmProdutosFiltro extends javax.swing.JFrame {

    String origem = null; // Variável para determinar qual form chamou esse, assim determina quais ações serão executadas
    // de acordo com a origem em questão.

    String situacao;
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat decimal = new DecimalFormat("#,##0.00");

    /**
     * Os métodos mostrarTela especifica qual form chamou esse, esse form pode
     * trocar informações (buscar e levar) com o form que o chamou.
     */
    private FrmVendas vendas;

    public void mostrarTela(FrmVendas vend) {
        situacao = vend.situacao; // na hora de passar o valor do produto, vai checar e ver se é o valor à vista ou à prazo.
        this.vendas = vend;
        this.origem = "requisicao";
        setVisible(true);
    }

    private FrmCompras compras;

    public void mostrarTela(FrmCompras comp) {
        this.compras = comp;
        this.origem = "requisicaoCompra";
        setVisible(true);
    }

    private FrmProdutos produtos;

    public void mostrarTela(FrmProdutos prod) {
        this.produtos = prod;
        this.origem = "produtos";
        setVisible(true);
    }

    public FrmProdutosFiltro() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Produtos = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro de Produtos");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(173, 198, 242));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        btnOk.setToolTipText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        tb_Produtos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Valor Compra", "Valor à Prazo", "Valor à Vista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Produtos.setRowHeight(20);
        jScrollPane1.setViewportView(tb_Produtos);
        if (tb_Produtos.getColumnModel().getColumnCount() > 0) {
            tb_Produtos.getColumnModel().getColumn(0).setPreferredWidth(10);
            tb_Produtos.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtrar Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        String texto = txtNome.getText();
        String valorCompra, valorVenda, valorVista;

        DefaultTableModel dados = (DefaultTableModel) tb_Produtos.getModel();
        dados.setNumRows(0);

        ProdutosDao dao = new ProdutosDao();
        Produtos obj = new Produtos();

        if (texto.equals("")) {

            List<Produtos> lista = dao.listarProdutos();

            for (Produtos p : lista) {
                valorCompra = String.valueOf(decimal.format(p.getValor_compra()));
                valorVenda = String.valueOf(decimal.format(p.getValor_venda()));
                valorVista = String.valueOf(decimal.format(p.getValor_vista()));
                dados.addRow(new Object[]{
                    p.getId(),
                    p.getNome(),
                    p.getQuantidade(),
                    valorCompra,
                    valorVenda,
                    valorVista
                });
            }
        } else {
            String nome = txtNome.getText() + "%";

            List<Produtos> lista = dao.consultarPorNome(nome);

            for (Produtos p : lista) {
                valorCompra = String.valueOf(decimal.format(p.getValor_compra()));
                valorVenda = String.valueOf(decimal.format(p.getValor_venda()));
                valorVista = String.valueOf(decimal.format(p.getValor_vista()));
                dados.addRow(new Object[]{
                    p.getId(),
                    p.getNome(),
                    p.getQuantidade(),
                    valorCompra,
                    valorVenda,
                    valorVista
                });
            }
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (origem.equals("produtos")) {

            int idValidacao = tb_Produtos.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                int id = Integer.parseInt(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 0).toString());

                ProdutosDao dao = new ProdutosDao();
                Produtos obj = new Produtos();
                obj = dao.consultarPorId(id);

                produtos.filtro = "sim";

                produtos.txtId.setText(String.valueOf(obj.getId()));
                produtos.txtNome.setText(obj.getNome());
                produtos.cbTipo.setSelectedItem(obj.getTipo());
                produtos.txtNcm.setText(obj.getNcm());
                produtos.txtCod_barras.setText(obj.getCod_barras());
                produtos.txtQuantidade.setText(String.valueOf(obj.getQuantidade()));
                String atualizacaoS = obj.getAtualizacao();
                try {
                    Date atualizacao = formato.parse(atualizacaoS);
                    produtos.txtAtualizacao.setDate(atualizacao);
                } catch (Exception e) {
                }
                produtos.txtValorCompra.setText(String.valueOf(decimal.format(obj.getValor_compra())));
                produtos.txtMargem_lucro.setText(String.valueOf(decimal.format(obj.getMargem_lucro())));
                produtos.txtValorVenda.setText(String.valueOf(decimal.format(obj.getValor_venda())));
                produtos.txtDesconto_vista.setText(String.valueOf(decimal.format(obj.getDesconto_vista())));
                produtos.txtValor_vista.setText(String.valueOf(decimal.format(obj.getValor_vista())));
                produtos.txtObservacoes.setText(obj.getObservacoes());

                this.dispose();
            }

        } else if (origem.equals("requisicao")) {

            int idValidacao = tb_Produtos.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                if (situacao.equals("A Vista")) {
                    vendas.txtIdProduto.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 0).toString());
                    vendas.txtNomeProduto.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 1).toString());
                    vendas.txtPreco.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 5).toString());
                    this.dispose();
                } else if (situacao.equals("A Prazo")) {
                    vendas.txtIdProduto.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 0).toString());
                    vendas.txtNomeProduto.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 1).toString());
                    vendas.txtPreco.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 4).toString());
                    this.dispose();
                }
                vendas.txtQtd.requestFocus();
                vendas.txtQtd.selectAll();

            }
        } else if (origem.equals("requisicaoCompra")) {

            int idValidacao = tb_Produtos.getSelectedRowCount();

            if (idValidacao == 0) {
                this.dispose();
            } else {
                compras.txtIdProduto.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 0).toString());
                compras.txtNomeProduto.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 1).toString());
                compras.txtPreco.setText(tb_Produtos.getValueAt(tb_Produtos.getSelectedRow(), 3).toString());
                compras.txtPreco.requestFocus();
                compras.txtPreco.selectAll();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);

    }//GEN-LAST:event_formWindowActivated

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String texto = txtNome.getText();
            String valorCompra, valorVenda, valorVista;

            DefaultTableModel dados = (DefaultTableModel) tb_Produtos.getModel();
            dados.setNumRows(0);

            Produtos obj = new Produtos();
            ProdutosDao dao = new ProdutosDao();

            if (texto.equals("")) {

                List<Produtos> lista = dao.listarProdutos();

                for (Produtos p : lista) {
                    valorCompra = String.valueOf(decimal.format(p.getValor_compra()));
                    valorVenda = String.valueOf(decimal.format(p.getValor_venda()));
                    valorVista = String.valueOf(decimal.format(p.getValor_vista()));
                    dados.addRow(new Object[]{
                        p.getId(),
                        p.getNome(),
                        p.getQuantidade(),
                        valorCompra,
                        valorVenda,
                        valorVista
                    });
                }

            } else {
                String nome = texto + "%";

                List<Produtos> lista = dao.consultarPorNome(nome);

                for (Produtos p : lista) {
                    valorCompra = String.valueOf(decimal.format(p.getValor_compra()));
                    valorVenda = String.valueOf(decimal.format(p.getValor_venda()));
                    valorVista = String.valueOf(decimal.format(p.getValor_vista()));
                    dados.addRow(new Object[]{
                        p.getId(),
                        p.getNome(),
                        p.getQuantidade(),
                        valorCompra,
                        valorVenda,
                        valorVista
                    });
                }
            }
        }

    }//GEN-LAST:event_txtNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutosFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tb_Produtos;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
