/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ContasPagDao;
import br.com.projeto.dao.ContasRecDao;
import br.com.projeto.model.ContasPag;
import br.com.projeto.model.ContasRec;
import br.com.projeto.model.Utilitarios;
import java.awt.Color;
import java.awt.Label;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Rafael Godoy
 */
public class FrmRelatorioDia extends javax.swing.JFrame {

    String dinTitulo = "", dinNome = "", dinEmissao = "", dinVencimento = "", dinPagamento = "", dinValor = "", dinTotal = "0";
    String credTitulo = "", credNome = "", credEmissao = "", credVencimento = "", credPagamento = "", credValor = "", credTotal = "0";
    String debTitulo = "", debNome = "", debEmissao = "", debVencimento = "", debPagamento = "", debValor = "", debTotal = "0";
    String chequeTitulo = "", chequeNome = "", chequeEmissao = "", chequeVencimento = "", chequePagamento = "", chequeValor = "", chequeTotal = "0";
    String pagoTitulo = "", pagoNome = "", pagoEmissao = "", pagoVencimento = "", pagoPagamento = "", pagoValor = "", pagoTotal = "0";
    String recebidoFinal = "0", pagoFinal = "0", totalFinal = "0";
    Double dinheiro = 0.0, credito = 0.0, debito = 0.0, cheque = 0.0, pago = 0.0, recebimentos = 0.0, pagamentos = 0.0, total = 0.0;
    boolean linhaDin = false, linhaCred = false, linhaDeb = false, linhaCheque = false, linhaPago = false;

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat decimal = new DecimalFormat("#,##0.00");

    public FrmRelatorioDia() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDataBusca = new com.toedter.calendar.JDateChooser();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblDinheiro = new javax.swing.JLabel();
        lblDinheiroT = new javax.swing.JLabel();
        lblDinheiroN = new javax.swing.JLabel();
        lblDinheiroE = new javax.swing.JLabel();
        lblDinheiroV = new javax.swing.JLabel();
        lblChequeTotMsg = new javax.swing.JLabel();
        lblDinheiroTot = new javax.swing.JLabel();
        lblDinheiroP = new javax.swing.JLabel();
        lblDinheiroVa = new javax.swing.JLabel();
        lblDinheiroTit = new javax.swing.JLabel();
        lblDinheiroNome = new javax.swing.JLabel();
        lblDinheiroEmissao = new javax.swing.JLabel();
        lblDinheiroVenc = new javax.swing.JLabel();
        lblDinheiroPag = new javax.swing.JLabel();
        lblDinheiroValor = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        lblCreditoT = new javax.swing.JLabel();
        lblCreditoTit = new javax.swing.JLabel();
        lblCreditoNome = new javax.swing.JLabel();
        lblCreditoN = new javax.swing.JLabel();
        lblCreditoE = new javax.swing.JLabel();
        lblCreditoEmissao = new javax.swing.JLabel();
        lblCreditoVenc = new javax.swing.JLabel();
        lblCreditoV = new javax.swing.JLabel();
        lblCreditoP = new javax.swing.JLabel();
        lblCreditoPag = new javax.swing.JLabel();
        lblCreditoTotMsg = new javax.swing.JLabel();
        lblCreditoTot = new javax.swing.JLabel();
        lblCreditoValor = new javax.swing.JLabel();
        lblCreditoVa = new javax.swing.JLabel();
        lblDebito = new javax.swing.JLabel();
        lblDebitoT = new javax.swing.JLabel();
        lblDebitoTit = new javax.swing.JLabel();
        lblDebitoNome = new javax.swing.JLabel();
        lblDebitoN = new javax.swing.JLabel();
        lblDebitoE = new javax.swing.JLabel();
        lblDebitoV = new javax.swing.JLabel();
        lblDebitoP = new javax.swing.JLabel();
        lblDebitoVa = new javax.swing.JLabel();
        lblDebitoValor = new javax.swing.JLabel();
        lblDebitoPag = new javax.swing.JLabel();
        lblDebitoVenc = new javax.swing.JLabel();
        lblDebitoEmissao = new javax.swing.JLabel();
        lblDebitoTotMsg = new javax.swing.JLabel();
        lblDebitoTot = new javax.swing.JLabel();
        lblChequeVa = new javax.swing.JLabel();
        lblChequeP = new javax.swing.JLabel();
        lblChequeV = new javax.swing.JLabel();
        lblChequeE = new javax.swing.JLabel();
        lblChequeN = new javax.swing.JLabel();
        lblChequeT = new javax.swing.JLabel();
        lblCheque = new javax.swing.JLabel();
        lblChequeTit = new javax.swing.JLabel();
        lblChequeNome = new javax.swing.JLabel();
        lblChequeEmissao = new javax.swing.JLabel();
        lblChequeVenc = new javax.swing.JLabel();
        lblChequePag = new javax.swing.JLabel();
        lblChequeValor = new javax.swing.JLabel();
        lblChequeTotMsg1 = new javax.swing.JLabel();
        lblChequeTot = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        lblPagoT = new javax.swing.JLabel();
        lblPagoTit = new javax.swing.JLabel();
        lblPagoNome = new javax.swing.JLabel();
        lblPagoN = new javax.swing.JLabel();
        lblPagoEmissao = new javax.swing.JLabel();
        lblPagoE = new javax.swing.JLabel();
        lblPagoV = new javax.swing.JLabel();
        lblPagoVenc = new javax.swing.JLabel();
        lblPagoP = new javax.swing.JLabel();
        lblPagoVa = new javax.swing.JLabel();
        lblPagoPag = new javax.swing.JLabel();
        lblPagoValor = new javax.swing.JLabel();
        lblPagoTotMsg = new javax.swing.JLabel();
        lblPagoTot = new javax.swing.JLabel();
        lblTotR = new javax.swing.JLabel();
        lblTotRec = new javax.swing.JLabel();
        lblTotP = new javax.swing.JLabel();
        lblTotPago = new javax.swing.JLabel();
        lblTotF = new javax.swing.JLabel();
        lblTotFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(173, 198, 242));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Relatório do Dia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Data da Busca:");

        txtDataBusca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDinheiro.setBackground(new java.awt.Color(102, 204, 255));
        lblDinheiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDinheiro.setText("Recebidos em Dinheiro");
        lblDinheiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiro.setOpaque(true);

        lblDinheiroT.setBackground(new java.awt.Color(204, 204, 204));
        lblDinheiroT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroT.setText("Titulo ");
        lblDinheiroT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroT.setOpaque(true);

        lblDinheiroN.setBackground(new java.awt.Color(204, 204, 204));
        lblDinheiroN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroN.setText("Nome");
        lblDinheiroN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroN.setOpaque(true);

        lblDinheiroE.setBackground(new java.awt.Color(204, 204, 204));
        lblDinheiroE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroE.setText("Emissão");
        lblDinheiroE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroE.setOpaque(true);

        lblDinheiroV.setBackground(new java.awt.Color(204, 204, 204));
        lblDinheiroV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroV.setText("Vencimento");
        lblDinheiroV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroV.setOpaque(true);

        lblChequeTotMsg.setBackground(new java.awt.Color(102, 204, 255));
        lblChequeTotMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeTotMsg.setText("Total:");
        lblChequeTotMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeTotMsg.setOpaque(true);

        lblDinheiroTot.setBackground(new java.awt.Color(102, 204, 255));
        lblDinheiroTot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDinheiroTot.setText("0");
        lblDinheiroTot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroTot.setOpaque(true);

        lblDinheiroP.setBackground(new java.awt.Color(204, 204, 204));
        lblDinheiroP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroP.setText("Pagamento");
        lblDinheiroP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroP.setOpaque(true);

        lblDinheiroVa.setBackground(new java.awt.Color(204, 204, 204));
        lblDinheiroVa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroVa.setText("Valor ");
        lblDinheiroVa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDinheiroVa.setOpaque(true);

        lblDinheiroTit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroTit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDinheiroNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDinheiroEmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDinheiroVenc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroVenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDinheiroPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDinheiroValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDinheiroValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCredito.setBackground(new java.awt.Color(102, 204, 255));
        lblCredito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCredito.setText("Recebidos em Crédito");
        lblCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCredito.setOpaque(true);

        lblCreditoT.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditoT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoT.setText("Titulo ");
        lblCreditoT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoT.setOpaque(true);

        lblCreditoTit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoTit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreditoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreditoN.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditoN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoN.setText("Nome");
        lblCreditoN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoN.setOpaque(true);

        lblCreditoE.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoE.setText("Emissão");
        lblCreditoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoE.setOpaque(true);

        lblCreditoEmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreditoVenc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoVenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreditoV.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditoV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoV.setText("Vencimento");
        lblCreditoV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoV.setOpaque(true);

        lblCreditoP.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoP.setText("Pagamento");
        lblCreditoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoP.setOpaque(true);

        lblCreditoPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreditoTotMsg.setBackground(new java.awt.Color(102, 204, 255));
        lblCreditoTotMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoTotMsg.setText("Total:");
        lblCreditoTotMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoTotMsg.setOpaque(true);

        lblCreditoTot.setBackground(new java.awt.Color(102, 204, 255));
        lblCreditoTot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCreditoTot.setText("0");
        lblCreditoTot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoTot.setOpaque(true);

        lblCreditoValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreditoVa.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditoVa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCreditoVa.setText("Valor ");
        lblCreditoVa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCreditoVa.setOpaque(true);

        lblDebito.setBackground(new java.awt.Color(102, 204, 255));
        lblDebito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDebito.setText("Recebidos em Débito");
        lblDebito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebito.setOpaque(true);

        lblDebitoT.setBackground(new java.awt.Color(204, 204, 204));
        lblDebitoT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoT.setText("Titulo ");
        lblDebitoT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoT.setOpaque(true);

        lblDebitoTit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoTit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDebitoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDebitoN.setBackground(new java.awt.Color(204, 204, 204));
        lblDebitoN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoN.setText("Nome");
        lblDebitoN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoN.setOpaque(true);

        lblDebitoE.setBackground(new java.awt.Color(204, 204, 204));
        lblDebitoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoE.setText("Emissão");
        lblDebitoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoE.setOpaque(true);

        lblDebitoV.setBackground(new java.awt.Color(204, 204, 204));
        lblDebitoV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoV.setText("Vencimento");
        lblDebitoV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoV.setOpaque(true);

        lblDebitoP.setBackground(new java.awt.Color(204, 204, 204));
        lblDebitoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoP.setText("Pagamento");
        lblDebitoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoP.setOpaque(true);

        lblDebitoVa.setBackground(new java.awt.Color(204, 204, 204));
        lblDebitoVa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoVa.setText("Valor ");
        lblDebitoVa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoVa.setOpaque(true);

        lblDebitoValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDebitoPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDebitoVenc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoVenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDebitoEmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDebitoTotMsg.setBackground(new java.awt.Color(102, 204, 255));
        lblDebitoTotMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebitoTotMsg.setText("Total:");
        lblDebitoTotMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoTotMsg.setOpaque(true);

        lblDebitoTot.setBackground(new java.awt.Color(102, 204, 255));
        lblDebitoTot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDebitoTot.setText("0");
        lblDebitoTot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDebitoTot.setOpaque(true);

        lblChequeVa.setBackground(new java.awt.Color(204, 204, 204));
        lblChequeVa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeVa.setText("Valor ");
        lblChequeVa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeVa.setOpaque(true);

        lblChequeP.setBackground(new java.awt.Color(204, 204, 204));
        lblChequeP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeP.setText("Pagamento");
        lblChequeP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeP.setOpaque(true);

        lblChequeV.setBackground(new java.awt.Color(204, 204, 204));
        lblChequeV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeV.setText("Vencimento");
        lblChequeV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeV.setOpaque(true);

        lblChequeE.setBackground(new java.awt.Color(204, 204, 204));
        lblChequeE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeE.setText("Emissão");
        lblChequeE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeE.setOpaque(true);

        lblChequeN.setBackground(new java.awt.Color(204, 204, 204));
        lblChequeN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeN.setText("Nome");
        lblChequeN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeN.setOpaque(true);

        lblChequeT.setBackground(new java.awt.Color(204, 204, 204));
        lblChequeT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeT.setText("Titulo ");
        lblChequeT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeT.setOpaque(true);

        lblCheque.setBackground(new java.awt.Color(102, 204, 255));
        lblCheque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCheque.setText("Recebidos em Cheque");
        lblCheque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCheque.setOpaque(true);

        lblChequeTit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeTit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChequeNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChequeEmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChequeVenc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeVenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChequePag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChequeValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChequeTotMsg1.setBackground(new java.awt.Color(102, 204, 255));
        lblChequeTotMsg1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChequeTotMsg1.setText("Total:");
        lblChequeTotMsg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeTotMsg1.setOpaque(true);

        lblChequeTot.setBackground(new java.awt.Color(102, 204, 255));
        lblChequeTot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChequeTot.setText("0");
        lblChequeTot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChequeTot.setOpaque(true);

        lblPago.setBackground(new java.awt.Color(102, 204, 255));
        lblPago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPago.setText("Pago pela Loja");
        lblPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPago.setOpaque(true);

        lblPagoT.setBackground(new java.awt.Color(204, 204, 204));
        lblPagoT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoT.setText("Titulo ");
        lblPagoT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoT.setOpaque(true);

        lblPagoTit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoTit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPagoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPagoN.setBackground(new java.awt.Color(204, 204, 204));
        lblPagoN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoN.setText("Nome");
        lblPagoN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoN.setOpaque(true);

        lblPagoEmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPagoE.setBackground(new java.awt.Color(204, 204, 204));
        lblPagoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoE.setText("Emissão");
        lblPagoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoE.setOpaque(true);

        lblPagoV.setBackground(new java.awt.Color(204, 204, 204));
        lblPagoV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoV.setText("Vencimento");
        lblPagoV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoV.setOpaque(true);

        lblPagoVenc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoVenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPagoP.setBackground(new java.awt.Color(204, 204, 204));
        lblPagoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoP.setText("Pagamento");
        lblPagoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoP.setOpaque(true);

        lblPagoVa.setBackground(new java.awt.Color(204, 204, 204));
        lblPagoVa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoVa.setText("Valor ");
        lblPagoVa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoVa.setOpaque(true);

        lblPagoPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPagoValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPagoTotMsg.setBackground(new java.awt.Color(102, 204, 255));
        lblPagoTotMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagoTotMsg.setText("Total:");
        lblPagoTotMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoTotMsg.setOpaque(true);

        lblPagoTot.setBackground(new java.awt.Color(102, 204, 255));
        lblPagoTot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPagoTot.setText("0");
        lblPagoTot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagoTot.setOpaque(true);

        lblTotR.setBackground(new java.awt.Color(204, 204, 204));
        lblTotR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotR.setText("Total Recebido:");
        lblTotR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotR.setOpaque(true);

        lblTotRec.setBackground(new java.awt.Color(102, 204, 255));
        lblTotRec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotRec.setForeground(new java.awt.Color(255, 0, 0));
        lblTotRec.setText("0");
        lblTotRec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotRec.setOpaque(true);

        lblTotP.setBackground(new java.awt.Color(204, 204, 204));
        lblTotP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotP.setText("Total Pago:");
        lblTotP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotP.setOpaque(true);

        lblTotPago.setBackground(new java.awt.Color(102, 204, 255));
        lblTotPago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotPago.setForeground(new java.awt.Color(255, 0, 0));
        lblTotPago.setText("0");
        lblTotPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotPago.setOpaque(true);

        lblTotF.setBackground(new java.awt.Color(204, 204, 204));
        lblTotF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotF.setText("Total Final:");
        lblTotF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotF.setOpaque(true);

        lblTotFinal.setBackground(new java.awt.Color(102, 204, 255));
        lblTotFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotFinal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotFinal.setText("0");
        lblTotFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotFinal.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDinheiroTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDinheiroT, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDinheiroN, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(lblDinheiroNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDinheiroE, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblDinheiroEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDinheiroV, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(lblDinheiroVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDinheiroPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDinheiroP, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblChequeTotMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDinheiroVa, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblDinheiroValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDinheiroTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditoTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreditoT, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditoN, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(lblCreditoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditoE, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblCreditoEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditoV, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(lblCreditoVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditoPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreditoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreditoTotMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditoVa, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblCreditoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreditoTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDebitoTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDebitoT, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDebitoN, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(lblDebitoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDebitoE, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblDebitoEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDebitoV, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(lblDebitoVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDebitoPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDebitoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDebitoTotMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDebitoVa, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblDebitoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDebitoTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChequeTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChequeT, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChequeN, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(lblChequeNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChequeE, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblChequeEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChequeV, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(lblChequeVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChequePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChequeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChequeTotMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChequeVa, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblChequeValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChequeTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPagoTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPagoT, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPagoN, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(lblPagoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPagoE, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblPagoEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPagoV, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(lblPagoVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPagoPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPagoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPagoTotMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPagoVa, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblPagoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPagoTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotR, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblTotRec, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblTotP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblTotPago, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblTotF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblTotFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDinheiro)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDinheiroT)
                    .addComponent(lblDinheiroN)
                    .addComponent(lblDinheiroE)
                    .addComponent(lblDinheiroV)
                    .addComponent(lblDinheiroP)
                    .addComponent(lblDinheiroVa))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDinheiroTit)
                    .addComponent(lblDinheiroNome)
                    .addComponent(lblDinheiroEmissao)
                    .addComponent(lblDinheiroVenc)
                    .addComponent(lblDinheiroPag)
                    .addComponent(lblDinheiroValor))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDinheiroTot)
                    .addComponent(lblChequeTotMsg))
                .addGap(18, 18, 18)
                .addComponent(lblCredito)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditoT)
                    .addComponent(lblCreditoN)
                    .addComponent(lblCreditoE)
                    .addComponent(lblCreditoV)
                    .addComponent(lblCreditoP)
                    .addComponent(lblCreditoVa))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditoTit)
                    .addComponent(lblCreditoNome)
                    .addComponent(lblCreditoEmissao)
                    .addComponent(lblCreditoVenc)
                    .addComponent(lblCreditoPag)
                    .addComponent(lblCreditoValor))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditoTot)
                    .addComponent(lblCreditoTotMsg))
                .addGap(18, 18, 18)
                .addComponent(lblDebito)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebitoT)
                    .addComponent(lblDebitoN)
                    .addComponent(lblDebitoE)
                    .addComponent(lblDebitoV)
                    .addComponent(lblDebitoP)
                    .addComponent(lblDebitoVa))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebitoTit)
                    .addComponent(lblDebitoNome)
                    .addComponent(lblDebitoEmissao)
                    .addComponent(lblDebitoVenc)
                    .addComponent(lblDebitoPag)
                    .addComponent(lblDebitoValor))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebitoTot)
                    .addComponent(lblDebitoTotMsg))
                .addGap(18, 18, 18)
                .addComponent(lblCheque)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChequeT)
                    .addComponent(lblChequeN)
                    .addComponent(lblChequeE)
                    .addComponent(lblChequeV)
                    .addComponent(lblChequeP)
                    .addComponent(lblChequeVa))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChequeTit)
                    .addComponent(lblChequeNome)
                    .addComponent(lblChequeEmissao)
                    .addComponent(lblChequeVenc)
                    .addComponent(lblChequePag)
                    .addComponent(lblChequeValor))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChequeTot)
                    .addComponent(lblChequeTotMsg1))
                .addGap(27, 27, 27)
                .addComponent(lblPago)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagoT)
                    .addComponent(lblPagoN)
                    .addComponent(lblPagoE)
                    .addComponent(lblPagoV)
                    .addComponent(lblPagoP)
                    .addComponent(lblPagoVa))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagoTit)
                    .addComponent(lblPagoNome)
                    .addComponent(lblPagoEmissao)
                    .addComponent(lblPagoVenc)
                    .addComponent(lblPagoPag)
                    .addComponent(lblPagoValor))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagoTot)
                    .addComponent(lblPagoTotMsg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotR)
                    .addComponent(lblTotRec)
                    .addComponent(lblTotF)
                    .addComponent(lblTotFinal)
                    .addComponent(lblTotP)
                    .addComponent(lblTotPago))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        Date hoje = new Date();
        txtDataBusca.setDate(hoje);

    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        /**
         * Com base na data inserida no campo de busca, é preenchido todos os
         * campos quando houver contas liquidadas referente aquela data. Cada
         * conta é filtrada pelo plano da baixa e adicionada na tabela desse
         * plano. Depois aparece a soma das baixas de cada plano. Ao final é
         * apresentado os valores de tudo o que foi recebido, pago e o valor
         * final (recebido - pago).
         */
        dinTitulo = "";
        dinNome = "";
        dinEmissao = "";
        dinVencimento = "";
        dinPagamento = "";
        dinValor = "";
        dinTotal = "0";
        credTitulo = "";
        credNome = "";
        credEmissao = "";
        credVencimento = "";
        credPagamento = "";
        credValor = "";
        credTotal = "0";
        debTitulo = "";
        debNome = "";
        debEmissao = "";
        debVencimento = "";
        debPagamento = "";
        debValor = "";
        debTotal = "0";
        chequeTitulo = "";
        chequeNome = "";
        chequeEmissao = "";
        chequeVencimento = "";
        chequePagamento = "";
        chequeValor = "";
        chequeTotal = "0";
        pagoTitulo = "";
        pagoNome = "";
        pagoEmissao = "";
        pagoVencimento = "";
        pagoPagamento = "";
        pagoValor = "";
        pagoTotal = "0";
        recebidoFinal = "0";
        pagoFinal = "0";
        totalFinal = "0";
        dinheiro = 0.0;
        credito = 0.0;
        debito = 0.0;
        cheque = 0.0;
        pago = 0.0;
        recebimentos = 0.0;
        pagamentos = 0.0;
        total = 0.0;
        linhaDin = false;
        linhaCred = false;
        linhaDeb = false;
        linhaCheque = false;
        linhaPago = false;

        lblDinheiroTit.setText("");
        lblDinheiroNome.setText("");
        lblDinheiroEmissao.setText("");
        lblDinheiroVenc.setText("");
        lblDinheiroPag.setText("");
        lblDinheiroValor.setText("");
        lblDinheiroTot.setText("0");

        lblCreditoTit.setText("");
        lblCreditoNome.setText("");
        lblCreditoEmissao.setText("");
        lblCreditoVenc.setText("");
        lblCreditoPag.setText("");
        lblCreditoValor.setText("");
        lblCreditoTot.setText("0");

        lblDebitoTit.setText("");
        lblDebitoNome.setText("");
        lblDebitoEmissao.setText("");
        lblDebitoVenc.setText("");
        lblDebitoPag.setText("");
        lblDebitoValor.setText("");
        lblDebitoTot.setText("0");

        lblChequeTit.setText("");
        lblChequeNome.setText("");
        lblChequeEmissao.setText("");
        lblChequeVenc.setText("");
        lblChequePag.setText("");
        lblChequeValor.setText("");
        lblChequeTot.setText("0");

        lblPagoTit.setText("");
        lblPagoNome.setText("");
        lblPagoEmissao.setText("");
        lblPagoVenc.setText("");
        lblPagoPag.setText("");
        lblPagoValor.setText("");
        lblPagoTot.setText("0");

        Date data = txtDataBusca.getDate();
        String dataBusca = formato.format(data);

        ContasRecDao daoRec = new ContasRecDao();
        List<ContasRec> listaRec = daoRec.filtrarContasRelatorioDia(dataBusca);

        for (ContasRec c : listaRec) {
            String tipo = c.getPlano().getTipo();
            String valor = String.valueOf(decimal.format(c.getValor_final()));
            String emissao = c.getEmissao();
            emissao = emissao.substring(8, 10) + "/" + emissao.substring(5, 7) + "/" + emissao.substring(0, 4);
            String vencimento = c.getVencimento();
            vencimento = vencimento.substring(8, 10) + "/" + vencimento.substring(5, 7) + "/" + vencimento.substring(0, 4);
            String pagamento = c.getBaixa();
            pagamento = pagamento.substring(8, 10) + "/" + pagamento.substring(5, 7) + "/" + pagamento.substring(0, 4);
            /**
             * após fazer a busca de todas as contas recebidas, é feito a
             * separação de acordo com o plano da baixa. As variáveis linha...
             * são pra identificar se há algum regitro salvo nesse plano. Caso
             * não haja, não será alterado os campos no formulário. Caso seja o
             * primeiro registro é armazenado na primeira linha, do contrário é
             * pulado uma linha do registro anterior.
             */
            if (tipo.equals("Dinheiro")) {
                if (dinTitulo.equals("")) {
                    dinTitulo = dinTitulo + c.getId();
                    dinNome = dinNome + c.getCliente().getNome();
                    dinEmissao = dinEmissao + emissao;
                    dinVencimento = dinVencimento + vencimento;
                    dinPagamento = dinPagamento + pagamento;
                    dinValor = dinValor + valor;
                    dinheiro = dinheiro + c.getValor_final();
                    dinTotal = String.valueOf(decimal.format(dinheiro));
                    linhaDin = true;
                } else {
                    dinTitulo = dinTitulo + "<br>" + c.getId();
                    dinNome = dinNome + "<br>" + c.getCliente().getNome();
                    dinEmissao = dinEmissao + "<br>" + emissao;
                    dinVencimento = dinVencimento + "<br>" + vencimento;
                    dinPagamento = dinPagamento + "<br>" + pagamento;
                    dinValor = dinValor + "<br>" + valor;
                    dinheiro = dinheiro + c.getValor_final();
                    dinTotal = String.valueOf(decimal.format(dinheiro));
                    linhaDin = true;
                }
            } else if (tipo.equals("Crédito")) {
                if (credTitulo.equals("")) {
                    credTitulo = credTitulo + c.getId();
                    credNome = credNome + c.getCliente().getNome();
                    credEmissao = credEmissao + emissao;
                    credVencimento = credVencimento + vencimento;
                    credPagamento = credPagamento + pagamento;
                    credValor = credValor + valor;
                    credito = credito + c.getValor_final();
                    credTotal = String.valueOf(decimal.format(credito));
                    linhaCred = true;
                } else {
                    credTitulo = credTitulo + "<br>" + c.getId();
                    credNome = credNome + "<br>" + c.getCliente().getNome();
                    credEmissao = credEmissao + "<br>" + emissao;
                    credVencimento = credVencimento + "<br>" + vencimento;
                    credPagamento = credPagamento + "<br>" + pagamento;
                    credValor = credValor + "<br>" + valor;
                    credito = credito + c.getValor_final();
                    credTotal = String.valueOf(decimal.format(credito));
                    linhaCred = true;
                }
            } else if (tipo.equals("Débito")) {
                if (debTitulo.equals("")) {
                    debTitulo = debTitulo + c.getId();
                    debNome = debNome + c.getCliente().getNome();
                    debEmissao = debEmissao + emissao;
                    debVencimento = debVencimento + vencimento;
                    debPagamento = debPagamento + pagamento;
                    debValor = debValor + valor;
                    debito = debito + c.getValor_final();
                    debTotal = String.valueOf(decimal.format(debito));
                    linhaDeb = true;
                } else {
                    debTitulo = debTitulo + "<br>" + c.getId();
                    debNome = debNome + "<br>" + c.getCliente().getNome();
                    debEmissao = debEmissao + "<br>" + emissao;
                    debVencimento = debVencimento + "<br>" + vencimento;
                    debPagamento = debPagamento + "<br>" + pagamento;
                    debValor = debValor + "<br>" + valor;
                    debito = debito + c.getValor_final();
                    debTotal = String.valueOf(decimal.format(debito));
                    linhaDeb = true;
                }
            } else if (tipo.equals("Cheque")) {
                if (chequeTitulo.equals("")) {
                    chequeTitulo = chequeTitulo + c.getId();
                    chequeNome = chequeNome + c.getCliente().getNome();
                    chequeEmissao = chequeEmissao + emissao;
                    chequeVencimento = chequeVencimento + vencimento;
                    chequePagamento = chequePagamento + pagamento;
                    chequeValor = chequeValor + valor;
                    cheque = cheque + c.getValor_final();
                    chequeTotal = String.valueOf(decimal.format(cheque));
                    linhaCheque = true;
                } else {
                    chequeTitulo = chequeTitulo + "<br>" + c.getId();
                    chequeNome = chequeNome + "<br>" + c.getCliente().getNome();
                    chequeEmissao = chequeEmissao + "<br>" + emissao;
                    chequeVencimento = chequeVencimento + "<br>" + vencimento;
                    chequePagamento = chequePagamento + "<br>" + pagamento;
                    chequeValor = chequeValor + "<br>" + valor;
                    cheque = cheque + c.getValor_final();
                    chequeTotal = String.valueOf(decimal.format(cheque));
                    linhaCheque = true;
                }
            }
        }

        ContasPagDao daoPag = new ContasPagDao();
        List<ContasPag> listaPag = daoPag.filtrarContasRelatorioDia(dataBusca);

        for (ContasPag c : listaPag) {
            String valor = String.valueOf(decimal.format(c.getValor_final()));
            String emissao = c.getEmissao();
            emissao = emissao.substring(8, 10) + "/" + emissao.substring(5, 7) + "/" + emissao.substring(0, 4);
            String vencimento = c.getVencimento();
            vencimento = vencimento.substring(8, 10) + "/" + vencimento.substring(5, 7) + "/" + vencimento.substring(0, 4);
            String pagamento = c.getBaixa();
            pagamento = pagamento.substring(8, 10) + "/" + pagamento.substring(5, 7) + "/" + pagamento.substring(0, 4);

            /**
             * após fazer a busca de todas as contas recebidas, é adicionado as
             * contas nos campos correspondentes. As variáveis linha... são pra
             * identificar se há algum regitro salvo nesse plano. Caso não haja,
             * não será alterado os campos no formulário. Caso seja o primeiro
             * registro é armazenado na primeira linha, do contrário é pulado
             * uma linha do registro anterior.
             */
            if (pagoTitulo.equals("")) {
                pagoTitulo = pagoTitulo + c.getId();
                pagoNome = pagoNome + c.getFornecedor().getNome();
                pagoEmissao = pagoEmissao + emissao;
                pagoVencimento = pagoVencimento + vencimento;
                pagoPagamento = pagoPagamento + pagamento;
                pagoValor = pagoValor + valor;
                pago = pago + c.getValor_final();
                pagoTotal = String.valueOf(decimal.format(pago));
                linhaPago = true;
            } else {
                pagoTitulo = pagoTitulo + "<br>" + c.getId();
                pagoNome = pagoNome + "<br>" + c.getFornecedor().getNome();
                pagoEmissao = pagoEmissao + "<br>" + emissao;
                pagoVencimento = pagoVencimento + "<br>" + vencimento;
                pagoPagamento = pagoPagamento + "<br>" + pagamento;
                pagoValor = pagoValor + "<br>" + valor;
                pago = pago + c.getValor_final();
                pagoTotal = String.valueOf(decimal.format(pago));
                linhaPago = true;
            }

        }

        /**
         * todos os planos que que tiverem algum registro liquidado na data da
         * busca, estará com sua linha igual a true, a seguir é feito o
         * preenchimento de todos os dados no formulário, cada variável é
         * alocada na label correspondente.
         */
        if (linhaDin == true) {
            lblDinheiroTit.setText("<html>" + dinTitulo + "</html>");
            lblDinheiroNome.setText("<html>" + dinNome + "</html>");
            lblDinheiroEmissao.setText("<html>" + dinEmissao + "</html>");
            lblDinheiroVenc.setText("<html>" + dinVencimento + "</html>");
            lblDinheiroPag.setText("<html>" + dinPagamento + "</html>");
            lblDinheiroValor.setText("<html>" + dinValor + "</html>");
            lblDinheiroTot.setText("<html>" + dinTotal + "</html>");
        }

        if (linhaCred == true) {
            lblCreditoTit.setText("<html>" + credTitulo + "</html>");
            lblCreditoNome.setText("<html>" + credNome + "</html>");
            lblCreditoEmissao.setText("<html>" + credEmissao + "</html>");
            lblCreditoVenc.setText("<html>" + credVencimento + "</html>");
            lblCreditoPag.setText("<html>" + credPagamento + "</html>");
            lblCreditoValor.setText("<html>" + credValor + "</html>");
            lblCreditoTot.setText("<html>" + credTotal + "</html>");
        }

        if (linhaDeb == true) {
            lblDebitoTit.setText("<html>" + debTitulo + "</html>");
            lblDebitoNome.setText("<html>" + debNome + "</html>");
            lblDebitoEmissao.setText("<html>" + debEmissao + "</html>");
            lblDebitoVenc.setText("<html>" + debVencimento + "</html>");
            lblDebitoPag.setText("<html>" + debPagamento + "</html>");
            lblDebitoValor.setText("<html>" + debValor + "</html>");
            lblDebitoTot.setText("<html>" + debTotal + "</html>");
        }

        if (linhaCheque == true) {
            lblChequeTit.setText("<html>" + chequeTitulo + "</html>");
            lblChequeNome.setText("<html>" + chequeNome + "</html>");
            lblChequeEmissao.setText("<html>" + chequeEmissao + "</html>");
            lblChequeVenc.setText("<html>" + chequeVencimento + "</html>");
            lblChequePag.setText("<html>" + chequePagamento + "</html>");
            lblChequeValor.setText("<html>" + chequeValor + "</html>");
            lblChequeTot.setText("<html>" + chequeTotal + "</html>");
        }

        if (linhaPago == true) {
            lblPagoTit.setText("<html>" + pagoTitulo + "</html>");
            lblPagoNome.setText("<html>" + pagoNome + "</html>");
            lblPagoEmissao.setText("<html>" + pagoEmissao + "</html>");
            lblPagoVenc.setText("<html>" + pagoVencimento + "</html>");
            lblPagoPag.setText("<html>" + pagoPagamento + "</html>");
            lblPagoValor.setText("<html>" + pagoValor + "</html>");
            lblPagoTot.setText("<html>" + pagoTotal + "</html>");
        }

        /**
         * é feito os cálculos de todos os valores e alocados nas lables
         * correspondentes.
         */
        recebimentos = dinheiro + credito + debito + cheque;
        pagamentos = pago;
        total = recebimentos - pagamentos;

        recebidoFinal = String.valueOf(decimal.format(recebimentos));
        pagoFinal = String.valueOf(decimal.format(pagamentos));
        totalFinal = String.valueOf(decimal.format(total));

        lblTotRec.setText(recebidoFinal);
        lblTotPago.setText(pagoFinal);
        lblTotFinal.setText(totalFinal);

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorioDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorioDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorioDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorioDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRelatorioDia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheque;
    private javax.swing.JLabel lblChequeE;
    private javax.swing.JLabel lblChequeEmissao;
    private javax.swing.JLabel lblChequeN;
    private javax.swing.JLabel lblChequeNome;
    private javax.swing.JLabel lblChequeP;
    private javax.swing.JLabel lblChequePag;
    private javax.swing.JLabel lblChequeT;
    private javax.swing.JLabel lblChequeTit;
    private javax.swing.JLabel lblChequeTot;
    private javax.swing.JLabel lblChequeTotMsg;
    private javax.swing.JLabel lblChequeTotMsg1;
    private javax.swing.JLabel lblChequeV;
    private javax.swing.JLabel lblChequeVa;
    private javax.swing.JLabel lblChequeValor;
    private javax.swing.JLabel lblChequeVenc;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblCreditoE;
    private javax.swing.JLabel lblCreditoEmissao;
    private javax.swing.JLabel lblCreditoN;
    private javax.swing.JLabel lblCreditoNome;
    private javax.swing.JLabel lblCreditoP;
    private javax.swing.JLabel lblCreditoPag;
    private javax.swing.JLabel lblCreditoT;
    private javax.swing.JLabel lblCreditoTit;
    private javax.swing.JLabel lblCreditoTot;
    private javax.swing.JLabel lblCreditoTotMsg;
    private javax.swing.JLabel lblCreditoV;
    private javax.swing.JLabel lblCreditoVa;
    private javax.swing.JLabel lblCreditoValor;
    private javax.swing.JLabel lblCreditoVenc;
    private javax.swing.JLabel lblDebito;
    private javax.swing.JLabel lblDebitoE;
    private javax.swing.JLabel lblDebitoEmissao;
    private javax.swing.JLabel lblDebitoN;
    private javax.swing.JLabel lblDebitoNome;
    private javax.swing.JLabel lblDebitoP;
    private javax.swing.JLabel lblDebitoPag;
    private javax.swing.JLabel lblDebitoT;
    private javax.swing.JLabel lblDebitoTit;
    private javax.swing.JLabel lblDebitoTot;
    private javax.swing.JLabel lblDebitoTotMsg;
    private javax.swing.JLabel lblDebitoV;
    private javax.swing.JLabel lblDebitoVa;
    private javax.swing.JLabel lblDebitoValor;
    private javax.swing.JLabel lblDebitoVenc;
    private javax.swing.JLabel lblDinheiro;
    private javax.swing.JLabel lblDinheiroE;
    private javax.swing.JLabel lblDinheiroEmissao;
    private javax.swing.JLabel lblDinheiroN;
    private javax.swing.JLabel lblDinheiroNome;
    private javax.swing.JLabel lblDinheiroP;
    private javax.swing.JLabel lblDinheiroPag;
    private javax.swing.JLabel lblDinheiroT;
    private javax.swing.JLabel lblDinheiroTit;
    private javax.swing.JLabel lblDinheiroTot;
    private javax.swing.JLabel lblDinheiroV;
    private javax.swing.JLabel lblDinheiroVa;
    private javax.swing.JLabel lblDinheiroValor;
    private javax.swing.JLabel lblDinheiroVenc;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPagoE;
    private javax.swing.JLabel lblPagoEmissao;
    private javax.swing.JLabel lblPagoN;
    private javax.swing.JLabel lblPagoNome;
    private javax.swing.JLabel lblPagoP;
    private javax.swing.JLabel lblPagoPag;
    private javax.swing.JLabel lblPagoT;
    private javax.swing.JLabel lblPagoTit;
    private javax.swing.JLabel lblPagoTot;
    private javax.swing.JLabel lblPagoTotMsg;
    private javax.swing.JLabel lblPagoV;
    private javax.swing.JLabel lblPagoVa;
    private javax.swing.JLabel lblPagoValor;
    private javax.swing.JLabel lblPagoVenc;
    private javax.swing.JLabel lblTotF;
    private javax.swing.JLabel lblTotFinal;
    private javax.swing.JLabel lblTotP;
    private javax.swing.JLabel lblTotPago;
    private javax.swing.JLabel lblTotR;
    private javax.swing.JLabel lblTotRec;
    private com.toedter.calendar.JDateChooser txtDataBusca;
    // End of variables declaration//GEN-END:variables
}
