/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.VendasNoCartaoDao;
import br.com.projeto.model.Utilitarios;
import br.com.projeto.model.VendasNoCartao;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Godoy
 */
public class FrmVendasNoCartaoFiltro extends javax.swing.JFrame {

    private String origem = null; // Variável para determinar qual form chamou esse, assim determina quais ações serão executadas
    // de acordo com a origem em questão.
    private boolean requisicao = false; // pra verificar se a busca é para uma requisição expecífica.
    private String reqTab; // pra preencher a tabela, se tiver número de requisição, é colocado o número, senão o campo fica em branco.
    private String data_baixa; // pra preencher a tabela, se tiver data de baixa, é colocado a data, senão o campo fica em branco.

    private Date hoje = new Date();

    List<VendasNoCartao> lista;

    Date dataInicio;

    Date dataFinal;

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

    DecimalFormat decimal = new DecimalFormat("#,##0.00");

    /**
     * O método mostrarTela especifica qual form chamou esse, esse form pode
     * trocar informações (buscar e levar) com o form que o chamou.
     */
    private FrmVendasNoCartao vendasCartao;

    public void mostrarTela(FrmVendasNoCartao vendCart) {
        this.origem = "vendasCartao";
        this.vendasCartao = vendCart;
        setVisible(true);
    }

    public FrmVendasNoCartaoFiltro() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtRequisicao = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbPeriodo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataInicio = new com.toedter.calendar.JDateChooser();
        txtDataFinal = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(173, 198, 242));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Status:");

        cbStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A baixar", "Baixado", "Cancelado", "Requisicao", "Todos os status" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Requisição:");

        txtRequisicao.setBackground(new java.awt.Color(240, 240, 240));
        txtRequisicao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRequisicao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(" Filtrar por:");

        cbPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emissão", "Vencimento", "Tudo" }));
        cbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeriodoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("De:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Até:");

        txtDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDataFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        btnOk.setToolTipText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Relatório de  Vendas No Cartão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        /**
         * há diversas formas de buscar as vendas no cartão, pelo nº da
         * requisição, ou pela junção do status e período, abaixo estão todos os
         * tipos de buscas.
         */
        VendasNoCartaoDao dao = new VendasNoCartaoDao();

        DefaultTableModel dados = (DefaultTableModel) vendasCartao.tb_Vendas.getModel();
        dados.setNumRows(0);

        if (requisicao == true) {

            String req = txtRequisicao.getText();

            if (req.equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o número da requisição que deseja consultar!");
                cbStatus.setSelectedItem("Requisicao");
            } else {
                lista = dao.buscarPorRequisicao(Integer.parseInt(req));

                for (VendasNoCartao v : lista) {

                    if (v.getId_requisicao() == 0) {
                        reqTab = "";
                    } else {
                        reqTab = String.valueOf(v.getId_requisicao());
                    }

                    String emissao = v.getEmissao();
                    emissao = emissao.substring(8) + "/" + emissao.substring(5, 7) + "/" + emissao.substring(0, 4);

                    String vencimento = v.getVencimento();
                    vencimento = vencimento.substring(8) + "/" + vencimento.substring(5, 7) + "/" + vencimento.substring(0, 4);

                    if (v.getData_baixa() != null) {
                        data_baixa = v.getData_baixa();
                        data_baixa = data_baixa.substring(8) + "/" + data_baixa.substring(5, 7) + "/" + data_baixa.substring(0, 4);
                    } else {
                        data_baixa = "";
                    }

                    String valorVenda = String.valueOf(decimal.format(v.getValorVenda()));
                    String taxa = String.valueOf(decimal.format(v.getPlano().getPorcentagem()));
                    String desconto = String.valueOf(decimal.format(v.getDesconto()));
                    String valorFinal = String.valueOf(decimal.format(v.getValorFinal()));

                    dados.addRow(new Object[]{
                        v.getId(),
                        reqTab,
                        emissao,
                        vencimento,
                        data_baixa,
                        v.getPlano().getNome(),
                        v.getSituacao(),
                        valorVenda,
                        taxa,
                        desconto,
                        valorFinal
                    });
                }
                this.dispose();
            }

        } else {
            if (cbStatus.getSelectedItem().equals("Todos os status")) {
                if (cbPeriodo.getSelectedItem().equals("Tudo")) {
                    lista = dao.listaVendas();
                } else if (cbPeriodo.getSelectedItem().equals("Emissão")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    lista = dao.listarEmissaoTudo(dataInicioF, dataFinalF);

                } else if (cbPeriodo.getSelectedItem().equals("Vencimento")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    lista = dao.listarVencimentoTudo(dataInicioF, dataFinalF);

                }
            } else if (cbStatus.getSelectedItem().equals("Baixado")) {

                if (cbPeriodo.getSelectedItem().equals("Tudo")) {
                    String status = "Baixado";
                    lista = dao.listarStatus(status);

                } else if (cbPeriodo.getSelectedItem().equals("Emissão")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    String status = "Baixado";

                    lista = dao.listarEmissaoStatus(dataInicioF, dataFinalF, status);

                } else if (cbPeriodo.getSelectedItem().equals("Vencimento")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    String status = "Baixado";

                    lista = dao.listarVencimentoStatus(dataInicioF, dataFinalF, status);
                }

            } else if (cbStatus.getSelectedItem().equals("A baixar")) {

                if (cbPeriodo.getSelectedItem().equals("Tudo")) {
                    String status = "A baixar";
                    lista = dao.listarStatus(status);

                } else if (cbPeriodo.getSelectedItem().equals("Emissão")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    String status = "A baixar";

                    lista = dao.listarEmissaoStatus(dataInicioF, dataFinalF, status);

                } else if (cbPeriodo.getSelectedItem().equals("Vencimento")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    String status = "A baixar";

                    lista = dao.listarVencimentoStatus(dataInicioF, dataFinalF, status);
                }

            } else if (cbStatus.getSelectedItem().equals("Cancelado")) {

                if (cbPeriodo.getSelectedItem().equals("Tudo")) {
                    String status = "Cancelado";
                    lista = dao.listarStatus(status);

                } else if (cbPeriodo.getSelectedItem().equals("Emissão")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    String status = "Cancelado";

                    lista = dao.listarEmissaoStatus(dataInicioF, dataFinalF, status);

                } else if (cbPeriodo.getSelectedItem().equals("Vencimento")) {

                    dataInicio = txtDataInicio.getDate();
                    String dataInicioF = formato.format(dataInicio);

                    dataFinal = txtDataFinal.getDate();
                    String dataFinalF = formato.format(dataFinal);

                    String status = "Cancelado";

                    lista = dao.listarVencimentoStatus(dataInicioF, dataFinalF, status);

                }
            }
            for (VendasNoCartao v : lista) {

                if (v.getId_requisicao() == 0) {
                    reqTab = "";
                } else {
                    reqTab = String.valueOf(v.getId_requisicao());
                }

                String emissao = v.getEmissao();
                emissao = emissao.substring(8) + "/" + emissao.substring(5, 7) + "/" + emissao.substring(0, 4);

                String vencimento = v.getVencimento();
                vencimento = vencimento.substring(8) + "/" + vencimento.substring(5, 7) + "/" + vencimento.substring(0, 4);

                if (v.getData_baixa() != null) {
                    data_baixa = v.getData_baixa();
                    data_baixa = data_baixa.substring(8) + "/" + data_baixa.substring(5, 7) + "/" + data_baixa.substring(0, 4);
                } else {
                    data_baixa = "";
                }

                String valorVenda = String.valueOf(decimal.format(v.getValorVenda()));
                String taxa = String.valueOf(decimal.format(v.getPlano().getPorcentagem()));
                String desconto = String.valueOf(decimal.format(v.getDesconto()));
                String valorFinal = String.valueOf(decimal.format(v.getValorFinal()));

                dados.addRow(new Object[]{
                    v.getId(),
                    reqTab,
                    emissao,
                    vencimento,
                    data_baixa,
                    v.getPlano().getNome(),
                    v.getSituacao(),
                    valorVenda,
                    taxa,
                    desconto,
                    valorFinal
                });
            }
            this.dispose();
        }


    }//GEN-LAST:event_btnOkActionPerformed

    private void cbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPeriodoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed

        // algumas configurações para caso a opção requisição esteja selecionada, ou caso estivesse e mude para outra opção.
        if (cbStatus.getSelectedItem().equals("Requisicao")) {
            requisicao = true;
            txtRequisicao.setEditable(true);
            txtRequisicao.setBackground(Color.white);
            cbPeriodo.setSelectedItem("Tudo");
            txtDataInicio.setCalendar(null);
            txtDataFinal.setCalendar(null);
            txtDataInicio.setEnabled(false);
            txtDataFinal.setEnabled(false);
            cbPeriodo.setEnabled(false);
        } else {
            requisicao = false;
            txtRequisicao.setEditable(false);
            txtRequisicao.setBackground(Color.LIGHT_GRAY);
            txtRequisicao.setText("");
            txtDataInicio.setEnabled(true);
            txtDataFinal.setEnabled(true);
            cbPeriodo.setEnabled(true);
        }

    }//GEN-LAST:event_cbStatusActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        requisicao = false;
        cbStatus.setSelectedItem("A baixar");
        cbPeriodo.setSelectedItem("Tudo");
        txtRequisicao.setText("");
        txtRequisicao.setEditable(false);
        txtDataInicio.setDate(hoje);
        txtDataFinal.setDate(hoje);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartaoFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartaoFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartaoFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartaoFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVendasNoCartaoFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JDateChooser txtDataFinal;
    private com.toedter.calendar.JDateChooser txtDataInicio;
    private javax.swing.JTextField txtRequisicao;
    // End of variables declaration//GEN-END:variables
}
