/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ClientesDao;
import br.com.projeto.dao.ItensVendasDao;
import br.com.projeto.dao.PlanosDao;
import br.com.projeto.dao.ProdutosDao;
import br.com.projeto.dao.VendasDao;
import br.com.projeto.dao.VendasNoCartaoDao;
import br.com.projeto.model.Clientes;
import br.com.projeto.model.ItensVendas;
import br.com.projeto.model.Planos;
import br.com.projeto.model.Produtos;
import br.com.projeto.model.Utilitarios;
import br.com.projeto.model.Vendas;
import br.com.projeto.model.VendasNoCartao;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Rafael Godoy
 */
public class FrmVendasNoCartao extends javax.swing.JFrame {

    /**
     * todas a vendas pagas no cartão, tem como resultado um novo registro de
     * "VendasNoCartão", nessa tela pode ser encontrado todas essas vendas. E
     * caso precisa ser incluso/alterado/excluso alguma venda manualmente,
     * também pode ser feito aqui. E por último, pode ser feito a baixa das
     * vendas que já foram confirmados o depósito no banco.
     */
    FrmPlanosFiltro PlaFil = new FrmPlanosFiltro();
    FrmVendasNoCartaoFiltro VendCartFil = new FrmVendasNoCartaoFiltro();

    DefaultTableModel dados;

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

    String botao = null; // variável para guardar se um cadastro está sendo criado/editado.
    private Date data_baixa; // usado pra fazer comparação, se está vazio ou não.
    private Date emissao;
    private Date vencimento;
    private String data_baixaS;
    private String emissaoS;
    private String vencimentoS;
    private int id_requisicao;

    DecimalFormat decimal = new DecimalFormat("#,##0.00");

    public FrmVendasNoCartao() {
        initComponents();

        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBaixar = new javax.swing.JButton();
        btnEstornar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Vendas = new javax.swing.JTable();
        dadosVenda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRequisição = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdPlano = new javax.swing.JTextField();
        txtPlano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTaxa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtEmissao = new com.toedter.calendar.JDateChooser();
        txtVencimento = new com.toedter.calendar.JDateChooser();
        txtDataBaixa = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Vendas");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(173, 198, 242));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vendas no Cartão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addGap(367, 367, 367))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        botoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botoes.setPreferredSize(new java.awt.Dimension(850, 65));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/filtro.png"))); // NOI18N
        btnFiltrar.setToolTipText("Filtrar Vendas");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/apagar.png"))); // NOI18N
        btnApagar.setToolTipText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/baixar.png"))); // NOI18N
        btnBaixar.setToolTipText("Baixar");
        btnBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixarActionPerformed(evt);
            }
        });

        btnEstornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estornar.png"))); // NOI18N
        btnEstornar.setToolTipText("Estornar");
        btnEstornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesLayout = new javax.swing.GroupLayout(botoes);
        botoes.setLayout(botoesLayout);
        botoesLayout.setHorizontalGroup(
            botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesLayout.createSequentialGroup()
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226)
                .addComponent(btnBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstornar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botoesLayout.setVerticalGroup(
            botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesLayout.createSequentialGroup()
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBaixar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEstornar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tb_Vendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_Vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Requisição", "Emissão", "Vencimento", "Data Baixa", "Plano", "Status", "Valor Venda", "Taxa", "Desconto", "Valor Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Vendas.setRowHeight(20);
        tb_Vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_VendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Vendas);
        if (tb_Vendas.getColumnModel().getColumnCount() > 0) {
            tb_Vendas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Vendas.getColumnModel().getColumn(1).setPreferredWidth(60);
            tb_Vendas.getColumnModel().getColumn(5).setPreferredWidth(120);
            tb_Vendas.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        dadosVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Requisição:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Status:");

        txtRequisição.setEditable(false);
        txtRequisição.setBackground(new java.awt.Color(255, 255, 255));
        txtRequisição.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Emissão:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Vencimento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Plano:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Data da Baixa:");

        txtIdPlano.setEditable(false);
        txtIdPlano.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdPlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdPlanoMouseClicked(evt);
            }
        });
        txtIdPlano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdPlanoKeyPressed(evt);
            }
        });

        txtPlano.setEditable(false);
        txtPlano.setBackground(new java.awt.Color(255, 255, 255));
        txtPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Valor Venda:");

        txtValorVenda.setEditable(false);
        txtValorVenda.setBackground(new java.awt.Color(255, 255, 255));
        txtValorVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorVendaKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Taxa:");

        txtTaxa.setEditable(false);
        txtTaxa.setBackground(new java.awt.Color(255, 255, 255));
        txtTaxa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Desconto:");

        txtDesconto.setEditable(false);
        txtDesconto.setBackground(new java.awt.Color(255, 255, 255));
        txtDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Valor Final:");

        txtValorFinal.setEditable(false);
        txtValorFinal.setBackground(new java.awt.Color(255, 255, 255));
        txtValorFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtStatus.setEditable(false);
        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Número:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEmissao.setBackground(new java.awt.Color(255, 255, 255));
        txtEmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmissao.setOpaque(false);

        txtVencimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDataBaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout dadosVendaLayout = new javax.swing.GroupLayout(dadosVenda);
        dadosVenda.setLayout(dadosVendaLayout);
        dadosVendaLayout.setHorizontalGroup(
            dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRequisição, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorFinal))
                    .addGroup(dadosVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlano))))
        );
        dadosVendaLayout.setVerticalGroup(
            dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(txtIdPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(txtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtRequisição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(dadosVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dadosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated


    }//GEN-LAST:event_formWindowActivated

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else {
            botao = "novo";

            btnNovo.setSelected(true);

            new Utilitarios().limpaTela_Habilita(dadosVenda);
            txtId.setEditable(false);

            txtDataBaixa.setCalendar(null);
            txtEmissao.setCalendar(null);
            txtVencimento.setCalendar(null);

            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            int id = dao.ultimoCadastro() + 1;
            txtId.setText(String.valueOf(id));
            txtRequisição.setText("");
            txtRequisição.setEditable(false);
            txtPlano.setEditable(false);
            txtStatus.setEditable(false);
            txtStatus.setText("A baixar");
            txtTaxa.setEditable(false);
            txtDesconto.setEditable(false);
            txtValorFinal.setEditable(false);
            txtDataBaixa.setEnabled(false);
        }


    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (botao == null) {
            VendCartFil.mostrarTela(this);

            new Utilitarios().limpaTela_Apenas(dadosVenda);

            txtDataBaixa.setCalendar(null);
            txtEmissao.setCalendar(null);
            txtVencimento.setCalendar(null);

        }

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        String id = txtId.getText();
        String status = txtStatus.getText();

        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser alterado!");
        } else if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (status.equals("Cancelado")) {
            JOptionPane.showMessageDialog(null, "Esse arquivo foi cancelado, não pode mais ser alterado!");
        } else if (botao == null && status != "Cancelado") {
            btnEditar.setSelected(true);
            botao = "editar";

            new Utilitarios().Habilita_Apenas(dadosVenda);
            txtId.setEditable(false);
            txtRequisição.setEditable(false);
            txtPlano.setEditable(false);
            txtStatus.setEditable(false);
            txtTaxa.setEditable(false);
            txtDesconto.setEditable(false);
            txtValorFinal.setEditable(false);

        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed

        String idS = txtId.getText();
        String status = txtStatus.getText();

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (idS.equals("")) {
            JOptionPane.showMessageDialog(null, "não há nenhum arquivo para ser excluído!");
        } else if (status.equals("Cancelado")) {
            JOptionPane.showMessageDialog(null, "Esse arquivo já foi cancelado!");
        } else {
            status = "Cancelado";
            int id = Integer.parseInt(idS);

            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            VendasNoCartao obj = new VendasNoCartao();
            obj.setSituacao(status);
            dao.editarStatus(status, id);
            txtStatus.setText(status);
            tb_Vendas.setValueAt(status, tb_Vendas.getSelectedRow(), 6);

            JOptionPane.showMessageDialog(null, "Arquivo cancelado com sucesso!");

        }

    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (botao == null) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser salvo!");
        } else if (botao.equals("novo")) {
            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            VendasNoCartao obj = new VendasNoCartao();

            emissao = txtEmissao.getDate();
            String emissaoF = formato.format(emissao);
            obj.setEmissao(emissaoF);

            vencimento = txtVencimento.getDate();
            String vencimentoF = formato.format(vencimento);
            obj.setVencimento(vencimentoF);

            Planos objPla = new Planos();
            objPla.setId(Integer.parseInt(txtIdPlano.getText()));

            obj.setPlano(objPla);
            obj.setSituacao(txtStatus.getText());
            obj.setValorVenda(Double.parseDouble(txtValorVenda.getText().replace(".", "").replace(",", ".")));
            obj.setDesconto(Double.parseDouble(txtDesconto.getText().replace(".", "").replace(",", ".")));
            obj.setValorFinal(Double.parseDouble(txtValorFinal.getText().replace(".", "").replace(",", ".")));
            dao.inserir(obj);
            JOptionPane.showMessageDialog(null, "Arquivo cadastrado com sucesso!");

            dados = (DefaultTableModel) tb_Vendas.getModel();

            String id = txtId.getText();

            emissaoF = emissaoF.substring(8) + "/" + emissaoF.substring(5, 7) + "/" + emissaoF.substring(0, 4);
            vencimentoF = vencimentoF.substring(8) + "/" + vencimentoF.substring(5, 7) + "/" + vencimentoF.substring(0, 4);

            dados.addRow(new Object[]{
                id,
                "",
                emissaoF,
                vencimentoF,
                "",
                obj.getPlano().getNome(),
                obj.getSituacao(),
                txtValorVenda.getText(),
                txtTaxa.getText(),
                txtDesconto.getText(),
                txtValorFinal.getText()
            });

            botao = null;

            new Utilitarios().limpaTela_Desabilita(dadosVenda);
            txtEmissao.setCalendar(null);
            txtVencimento.setCalendar(null);
            btnNovo.setSelected(false);
        } else if (botao.equals("editar")) {
            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            VendasNoCartao obj = new VendasNoCartao();

            int id = Integer.parseInt(txtId.getText());
            obj.setId(id);

            String requisicao = txtRequisição.getText();
            if (requisicao.equals("")) {

            } else {
                obj.setId_requisicao(Integer.parseInt(requisicao));
            }

            emissao = txtEmissao.getDate();
            String emissaoF = formato.format(emissao);
            obj.setEmissao(emissaoF);

            vencimento = txtVencimento.getDate();
            String vencimentoF = formato.format(vencimento);
            obj.setVencimento(vencimentoF);

            String status = txtStatus.getText();

            if (status.equals("Baixado")) {
                data_baixa = txtDataBaixa.getDate();
                data_baixaS = formato.format(data_baixa);
                obj.setData_baixa(data_baixaS);
                data_baixaS = data_baixaS.substring(8) + "/" + data_baixaS.substring(5, 7) + "/" + data_baixaS.substring(0, 4);
            } else {
                data_baixaS = "";
            }

            Planos objPla = new Planos();
            objPla.setId(Integer.parseInt(txtIdPlano.getText()));

            obj.setPlano(objPla);
            obj.setSituacao(txtStatus.getText());
            obj.setValorVenda(Double.parseDouble(txtValorVenda.getText().replace(".", "").replace(",", ".")));
            obj.setDesconto(Double.parseDouble(txtDesconto.getText().replace(".", "").replace(",", ".")));
            obj.setValorFinal(Double.parseDouble(txtValorFinal.getText().replace(".", "").replace(",", ".")));
            dao.editar(obj);

            dados = (DefaultTableModel) tb_Vendas.getModel();

            emissaoF = emissaoF.substring(8) + "/" + emissaoF.substring(5, 7) + "/" + emissaoF.substring(0, 4);
            vencimentoF = vencimentoF.substring(8) + "/" + vencimentoF.substring(5, 7) + "/" + vencimentoF.substring(0, 4);

            for (int i = 0; i < dados.getRowCount(); i++) {
                // identifica qual linha da tabela está sendo alterada, e mostra as modificações nela.
                int id_linha = Integer.parseInt(dados.getValueAt(i, 0).toString());

                if (id == id_linha) {
                    dados.setValueAt(id, i, 0);
                    dados.setValueAt(requisicao, i, 1);
                    dados.setValueAt(emissaoF, i, 2);
                    dados.setValueAt(vencimentoF, i, 3);
                    dados.setValueAt(data_baixaS, i, 4);
                    dados.setValueAt(txtPlano.getText(), i, 5);
                    dados.setValueAt(obj.getSituacao(), i, 6);
                    dados.setValueAt(txtValorVenda.getText(), i, 7);
                    dados.setValueAt(txtTaxa.getText(), i, 8);
                    dados.setValueAt(txtDesconto.getText(), i, 9);
                    dados.setValueAt(txtValorFinal.getText(), i, 10);
                }
            }
            botao = null;

            new Utilitarios().limpaTela_Desabilita(dadosVenda);
            txtEmissao.setCalendar(null);
            txtVencimento.setCalendar(null);
            txtDataBaixa.setCalendar(null);
            btnEditar.setSelected(false);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        if (botao == null) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser cancelado!");
        } else if (botao.equals("novo")) {
            new Utilitarios().limpaTela_Desabilita(dadosVenda);
            btnNovo.setSelected(false);
            botao = null;
        } else if (botao.equals("editar")) {
            btnEditar.setSelected(false);

            new Utilitarios().Desabilita_Apenas(dadosVenda);

            int id = Integer.parseInt(txtId.getText());
            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            VendasNoCartao obj = new VendasNoCartao();
            obj = dao.buscarPorId(id);

            if (obj.getData_baixa() != null) {
                data_baixaS = obj.getData_baixa();
                try {
                    data_baixa = formato.parse(data_baixaS);
                } catch (Exception e) {
                }
            } else {
                txtDataBaixa.setCalendar(null);
            }

            emissaoS = obj.getEmissao();
            try {
                Date emissao = formato.parse(emissaoS);
            } catch (Exception e) {
            }

            txtEmissao.setDate(emissao);

            vencimentoS = obj.getVencimento();
            try {
                Date vencimento = formato.parse(vencimentoS);
            } catch (Exception e) {
            }

            txtVencimento.setDate(vencimento);

            txtRequisição.setText(String.valueOf(obj.getId_requisicao()));
            txtIdPlano.setText(String.valueOf(obj.getPlano().getId()));
            txtPlano.setText(obj.getPlano().getNome());
            txtStatus.setText(obj.getSituacao());
            txtValorVenda.setText(String.valueOf(decimal.format(obj.getValorVenda())));
            txtTaxa.setText(String.valueOf(decimal.format(obj.getPlano().getPorcentagem())));
            txtDesconto.setText(String.valueOf(decimal.format(obj.getDesconto())));
            txtValorFinal.setText(String.valueOf(decimal.format(obj.getValorFinal())));

            botao = null;
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarActionPerformed

        String status = txtStatus.getText();
        String idS = txtId.getText();

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (status.equals("Cancelado")) {
            JOptionPane.showMessageDialog(null, "Esse arquivo foi cancelado!");
        } else if (status.equals("Baixado")) {
            JOptionPane.showMessageDialog(null, "Esse arquivo já foi baixado!");
        } else if (idS.equals("")) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser baixado!");
        } else {
            // muda o status para baixado e coloca a data da baixa.
            status = "Baixado";
            txtStatus.setText(status);

            tb_Vendas.setValueAt("Baixado", tb_Vendas.getSelectedRow(), 6);
            Date baixa = new Date();
            txtDataBaixa.setDate(baixa);
            data_baixaS = formato.format(baixa);
            String data_baixaF = data_baixaS.substring(8) + "/" + data_baixaS.substring(5, 7) + "/" + data_baixaS.substring(0, 4);
            tb_Vendas.setValueAt(data_baixaF, tb_Vendas.getSelectedRow(), 4);

            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            VendasNoCartao obj = new VendasNoCartao();
            int id = Integer.parseInt(idS);

            dao.editarStatus_Baixa(status, data_baixaS, id);

            JOptionPane.showMessageDialog(null, "Arquivo baixado com sucesso!");

        }


    }//GEN-LAST:event_btnBaixarActionPerformed

    private void btnEstornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstornarActionPerformed

        String status = txtStatus.getText();
        String idS = txtId.getText();

        if (botao == "novo" || botao == "editar") {
            JOptionPane.showMessageDialog(null, "Há um arquivo aberto. Cancele ou Salve ele antes de "
                    + "realizar essa operação!");
        } else if (status.equals("Cancelado")) {
            JOptionPane.showMessageDialog(null, "Esse arquivo foi cancelado!");
        } else if (status.equals("A baixar")) {
            JOptionPane.showMessageDialog(null, "Esse arquivo não está baixado!");
        } else if (idS.equals("")) {
            JOptionPane.showMessageDialog(null, "Não há nenhum arquivo para ser estornado!");
        } else {
            // muda o status para a baixa e apaga a data da baixa.
            status = "A baixar";

            tb_Vendas.setValueAt(status, tb_Vendas.getSelectedRow(), 6);
            tb_Vendas.setValueAt("", tb_Vendas.getSelectedRow(), 4);

            txtStatus.setText(status);
            txtDataBaixa.setCalendar(null);
            String data_baixa = null;

            VendasNoCartaoDao dao = new VendasNoCartaoDao();
            int id = Integer.parseInt(txtId.getText());
            dao.editarStatus_Baixa(status, data_baixa, id);

            JOptionPane.showMessageDialog(null, "Arquivo estornado com sucesso!");

        }

    }//GEN-LAST:event_btnEstornarActionPerformed

    private void tb_VendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_VendasMouseClicked

        if (botao == "novo" || botao == "editar") {

        } else {

            // pega os dados da linha selecionada, e coloca em seus respectivos campos.
            VendasNoCartao obj = new VendasNoCartao();
            VendasNoCartaoDao dao = new VendasNoCartaoDao();

            int id = Integer.parseInt(tb_Vendas.getValueAt(tb_Vendas.getSelectedRow(), 0).toString());

            obj = dao.buscarPorId(id);

            txtId.setText(String.valueOf(id));

            int requisicao = obj.getId_requisicao();
            if (requisicao == 0) {
                txtRequisição.setText("");
            } else {
                txtRequisição.setText(String.valueOf(obj.getId_requisicao()));
            }

            emissaoS = obj.getEmissao();
            try {
                emissao = formato.parse(emissaoS);
                txtEmissao.setDate(emissao);
            } catch (Exception e) {
            }

            vencimentoS = obj.getVencimento();
            try {
                vencimento = formato.parse(vencimentoS);
                txtVencimento.setDate(vencimento);
            } catch (Exception e) {
            }

            data_baixaS = obj.getData_baixa();
            if (data_baixaS == null) {
                txtDataBaixa.setCalendar(null);
            } else {
                data_baixaS = obj.getData_baixa();
                try {
                    data_baixa = formato.parse(data_baixaS);
                    txtDataBaixa.setDate(data_baixa);
                } catch (Exception e) {
                }
            }
            txtIdPlano.setText(String.valueOf(obj.getPlano().getId()));
            txtPlano.setText(obj.getPlano().getNome());
            txtStatus.setText(obj.getSituacao());
            txtValorVenda.setText(String.valueOf(decimal.format(obj.getValorVenda())));
            txtTaxa.setText(String.valueOf(decimal.format(obj.getPlano().getPorcentagem())));
            txtDesconto.setText(String.valueOf(decimal.format(obj.getDesconto())));
            txtValorFinal.setText(String.valueOf(decimal.format(obj.getValorFinal())));
        }


    }//GEN-LAST:event_tb_VendasMouseClicked

    private void txtIdPlanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdPlanoMouseClicked

        if (evt.getClickCount() == 2) {
            PlaFil.MostrarTelaCart(this);
        }

    }//GEN-LAST:event_txtIdPlanoMouseClicked

    private void txtValorVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorVendaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String plano = txtPlano.getText();

            if (plano.equals("")) {
                JOptionPane.showMessageDialog(null, "Primeiro, escolha o plano da operação!");
            } else {
                //ao dar enter no valor, preenche os outros campos, com base no plano escolhido.

                Double valorVenda = Double.parseDouble(txtValorVenda.getText().replace(".", "").replace(",", "."));
                Double taxa = Double.parseDouble(txtTaxa.getText().replace(".", "").replace(",", "."));
                Double desconto = (valorVenda / 100) * taxa;
                txtValorVenda.setText(String.valueOf(decimal.format(valorVenda)));
                txtTaxa.setText(String.valueOf(decimal.format(taxa)));
                txtDesconto.setText(String.valueOf(decimal.format(desconto)));
                Double valorFinal = valorVenda - desconto;
                txtValorFinal.setText(String.valueOf(decimal.format(valorFinal)));
            }

        }
    }//GEN-LAST:event_txtValorVendaKeyPressed

    private void txtIdPlanoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPlanoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int id_plano = Integer.parseInt(txtIdPlano.getText());
            //ao dar enter no plano, preenche os outros campos, com base nesse plano escolhido.

            Planos objPla = new Planos();
            PlanosDao daoPla = new PlanosDao();

            objPla = daoPla.consultarPorId(id_plano);

            txtPlano.setText(objPla.getNome());
            txtTaxa.setText(String.valueOf(decimal.format(objPla.getPorcentagem())));

            String valorS = txtValorVenda.getText();

            if (valorS.equals("")) {
            } else {
                Double valorVenda = Double.parseDouble(txtValorVenda.getText().replace(".", "").replace(",", "."));
                Double taxa = Double.parseDouble(txtTaxa.getText().replace(".", "").replace(",", "."));
                Double desconto = (valorVenda / 100) * taxa;
                txtValorVenda.setText(String.valueOf(decimal.format(valorVenda)));

                txtDesconto.setText(String.valueOf(decimal.format(desconto)));
                Double valorFinal = valorVenda - desconto;
                txtValorFinal.setText(String.valueOf(decimal.format(valorFinal)));
            }
            txtValorVenda.requestFocus();
            txtValorVenda.selectAll();
        }

    }//GEN-LAST:event_txtIdPlanoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendasNoCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVendasNoCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoes;
    public javax.swing.JButton btnApagar;
    public javax.swing.JButton btnBaixar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEstornar;
    public javax.swing.JButton btnFiltrar;
    public javax.swing.JButton btnNovo;
    public javax.swing.JButton btnSair;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JPanel dadosVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tb_Vendas;
    private com.toedter.calendar.JDateChooser txtDataBaixa;
    private javax.swing.JTextField txtDesconto;
    private com.toedter.calendar.JDateChooser txtEmissao;
    private javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIdPlano;
    public javax.swing.JTextField txtPlano;
    private javax.swing.JTextField txtRequisição;
    private javax.swing.JTextField txtStatus;
    public javax.swing.JTextField txtTaxa;
    private javax.swing.JTextField txtValorFinal;
    public javax.swing.JTextField txtValorVenda;
    private com.toedter.calendar.JDateChooser txtVencimento;
    // End of variables declaration//GEN-END:variables

}
